### ISSUE TITLE
Integrate Cypress.io

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#10]
# Feature
## Blocked!
until #17 and #164 are accomplished, there will be too much churn to really justify the e2e tests that I'm hoping to create.

## Why is this feature being added?

[Cypress.io](https://cypress.io)
Because we want the best e2e and integration testing the industry has to offer 💪 

## What should your feature do?
TBA

**Comment by takethefake** [comment]
would be interested in doing this when the time is ready!

**Comment by kylemh** [comment]
Once #164 and #17 are completed, I can get going on setting up Cypress configuration so that we can begin to add e2e testing per page 💃 

Thanks for being ready to step up to the plate.

**Comment by ariaaskarijob** [comment]
Would love to know when this is ready to contribute and collab!

**Comment by kylemh** [comment]
Closed in #379 

Will add more issues for e2e test specs later!
