### ISSUE TITLE
In Join form, password validation message not displaying correctly 

### ISSUE THREAD

**Issue by thecodestuff** [OperationCode/front-end#1033]
When a user doesn't supply a password which include combination of lower case and uppercase letters , a validation message flashes beside password field .This message is rendering outside of assigned div due to its length . see below screenshot 

![Screenshot from 2020-01-26 12-05-27](https://user-images.githubusercontent.com/35068786/73131788-49937180-4037-11ea-9b5f-ee2be97d409f.png)

To reproduce this again 
1. Visit https://operationcode.org/join 
2. In password field supply a password with only lower or number characters ,you will see the validation message .

I solved it already by tweaking its css little bit as seen in screenshot below 

![Screenshot from 2020-01-26 11-50-57](https://user-images.githubusercontent.com/35068786/73131838-18677100-4038-11ea-9a23-89ee4046ad4e.png)

**Comment by kylemh** [comment]
This issue is being handled by the original reporter.

**Comment by thecodestuff** [comment]
Thanks @kylemh  for assigning me this .

**Comment by kylemh** [comment]
Closed in #1034
