### ISSUE TITLE
Adjust .browserslistrc to exclude Internet Explorer

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1045]
# Feature request
While not ideal visually, we've still done our best to support IE11.

We haven't had a single visitor using the Internet Explorer Browser in 3 months according to Google Analytics. Since it's so unpopular, we can stop supporting it entirely. **That requires changing the `.browserslistrc`.**

Aside from this change, this issue can serve as weak PSA that we are also allowed to use CSS Grid in this repo now. I won't make any tickets to update things to using grid, because that seems unnecessary, but yeah...

## Proposed solution
Please refer to [this issue](https://github.com/browserslist/browserslist/issues/137) regarding excluding Internet Explorer from our [.browserslistrc](https://github.com/OperationCode/front-end/blob/master/.browserslistrc).

**Comment by ivanmartinezmorales** [comment]
Has anyone picked up this ticket? I'd like to pick it up.

**Comment by ivanmartinezmorales** [comment]
Actually, looks like someone picked up this ticket. https://github.com/OperationCode/front-end/commit/70c063d49d9c858ee07d2fd89aa8f90d6d8bec27

**Comment by ivanmartinezmorales** [comment]
Okay, I took a look at the deploy logs on Netlify and the storybook creation is failing with the following error: 

`9:12:15 PM: ERR! Module build failed: BrowserslistError: Unknown browser IEMob`

Failure in Zeit was as follows ```

  | Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
-- | --```

**Comment by kylemh** [comment]
Sorry if you spent any time on this. The issue was resolved as you mentioned - just forgot to tie the PR to this issue.

Resolved in https://github.com/OperationCode/front-end/pull/1047
