### ISSUE TITLE
Add link for VA's official VET-TEC providers

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/front-end#1054]
# Feature request
From Tom Cal - right now, we don't provide any direct connection to the VA's list of VET-TEC providers.

## Proposed solution
Add a link for the VA's official list of Vet Tec providers, near / just below the "SCHOOLS ACCEPTING VET TEC"  button filter.

https://www.benefits.va.gov/GIBILL/FGIB/VetTecTrainingProviders.asp 

note from Conrad - There are a few different ways we can refer directly to the VA website, UX-wise; open to suggestions.

**Comment by kylemh** [comment]
<img width="582" alt="Screen Shot 2020-02-29 at 11 40 02 AM" src="https://user-images.githubusercontent.com/9523719/75611405-3f5a0c80-5ae8-11ea-8563-07f881265c3c.png">

Must have missed this!
