### ISSUE TITLE
Add VET-TEC field to code schools submission form

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/front-end#1055]
# Feature request
From Tom Cal;

In the form for submitting information about code schools at https://api.operationcode.org/forms/codeschool ,
I suggest the following changes:
-- Add a field for "Vet Tec eligible?" (Yes/No)
-- Change "VA Accredited?" to "GI Bill eligible?" (Yes/No)

**Comment by kylemh** [comment]
Discussed on Slack
