### ISSUE TITLE
create-component script doesn't create correctly named CSS file

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1071]
# Bug Report
## What is the current behavior?
Running `yarn create-component AnyComponent` yields a new folder in the `components` folder, but the CSS file is titled `AnyComponent.css`.

## What is the expected behavior?
It should be titled `AnyComponent.module.css`.

**Comment by ivanmartinezmorales** [comment]
I can take a look at this issue. 💯

**Comment by AranzaBonanza** [comment]
Apologies for being late, I'd like to take it if possible.
