### ISSUE TITLE
Integrate label system into this repository

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#11]
I brought over a few labels that I needed immediately, but figured anybody could be welcome to add them if they have free time.

Please put everything found [here](https://github.com/OperationCode/operationcode_frontend/labels) over into [here](https://github.com/OperationCode/front-end/labels)

**Comment by chrismgonzalez** [comment]
I can tackle this one

**Comment by kylemh** [comment]
Assigning myself as a placeholder

**Comment by chrismgonzalez** [comment]
Complete
