### ISSUE TITLE
Make all blog articles render their content nicely

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1114]
# Feature request
Blogs are rendered with one fragment and are using the Container element which is flex row

## Proposed solution
https://github.com/OperationCode/front-end/blob/master/pages/blog/%5Barticle%5D.js#L49

Just wrap Article in a flex column container where everything is left-aligned.

Test that things look pretty at `/blog/hello-world`

**Comment by kelsyvghn** [comment]
can I take this as my very first issue? Is there a deadline for it to be completed as well?

**Comment by kylemh** [comment]
We would love for you to contribute! No deadline, but also we don’t allow issue claiming. If you do it, you do it!

**Comment by kelsyvghn** [comment]
Ok great!

**Comment by kelsyvghn** [comment]
I made a PR
