### ISSUE TITLE
Create blog index page

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1115]
# Feature request
We need a page in `/pages/blog/index.js` that acts as a system of listing the available blogs and rendering that list as pretty links that display meta data.

## Proposed solution
The page should use SSG like the [dynamic blog routes file](https://github.com/OperationCode/front-end/blob/main/pages/blog/%5Barticle%5D.js) to get a list of the articles and pass the array as a prop. For now, let's just use lodash string functions to convert the filename to a human-readable title and list the articles as links.

[Documentation for `getStaticPaths`](https://nextjs.org/docs/basic-features/data-fetching#getstaticpaths-static-generation)

Let's emulate FreeCodeCamp's [News page](https://www.freecodecamp.org/news/) as inspiration for the design.

**Comment by ksmacleod99** [comment]
@kylemh it appears #1114 has been resolved. Do we still need the ‘Status: Blocked’ label?

**Comment by kylemh** [comment]
No, good shout!

**Comment by adithyaakrishna** [comment]
@kylemh Can I work on this issue?

**Comment by kylemh** [comment]
You can work on any issue that is devoid of an assignee.

**Comment by prokorpio** [comment]
Hi @adithyaakrishna are you actively working on this?

**Comment by adithyaakrishna** [comment]
@prokorpio Hey, You can work on that. I'm currently held up with my project work.
I worked a lil bit on that but not enough to make a PR though😶

**Comment by prokorpio** [comment]
Nice! Thanks @adithyaakrishna. I'll give this a shot.

**Comment by kylemh** [comment]
Gonna reopen cuz it was gradual progress!

**Comment by thinkverse** [comment]
Hi there, saw this was re-opened. Didn't see any UI for it, but read FreeCodeCamp news page was of interest. Would this UI be acceptable? I made a quick [mobile version] and a [desktop version], though desktop is just a scaled-up version of the mobile one.

[mobile version]: https://www.figma.com/file/RetePbr16IAc9VA8i67tjc/Mobile
[desktop version]: https://www.figma.com/file/cai87NO3nht52NpkRpjhFP/Desktop

**Comment by kylemh** [comment]
You can see that the routing logic is hooked up - https://www.operationcode.org/blog

We just need a UI now, so your designs are PERFECT. I think the only thing I'd recommend is putting each of your "article entries" into a Card component. Do you want to execute on this or did you want to leave a design?

**Comment by thinkverse** [comment]
I could get on that yeah. Forked it and took a look at the storybook, didn't find a card that fits currently.
Should I create a new `PostCard` or `BlogCard` component for this? 🤔&nbsp; Wouldn't want to create it unnecessarily.

**Comment by kylemh** [comment]
Is there a reason the UI you defined would work inside of our existing base Card component?

**Comment by thinkverse** [comment]
Well, a card component can be pretty versatile sometimes. So I looked to see if it could be done with an existing card component. But since the base card only takes one base parameter which is the node `children`.

I figured the best course of action would be to make a new `BlogCard` component instead. But then again, since it takes a node `BlogIndex` could have the element node built in the index itself and pass that to the base card since it accepts a node.

**Comment by kylemh** [comment]
That means that it can fit anything. You would just pass it a React Fragment or div to group the elements in your design.

**Comment by cbituin** [comment]
@thinkverse Hows the progress? If you haven't had a chance, no worries. I will try to give it a go

**Comment by calincionca35** [comment]
Hi Conrad, are you still working on this issue?

**Comment by cbituin** [comment]
> @cbituin Hi Conrad, are you still working on this issue?

Nope it's all yours @calincionca35 👌
