### ISSUE TITLE
Flush out OpCode user profile page and easy access to slack after signup

### ISSUE THREAD

**Issue by jeffsnff** [OperationCode/front-end#1125]
# Feature request

Display the users information after signup / login on users profile page so the user will be able to see what exactly they have entered and can decided to update profile accordingly. As well as add a link onto profile page to either... 

  1. Request a new slack invite ( in case said user lost theirs )
or
  2. Link to the page [Find Your Community](https://slack.com/get-started#/find) ( again in case user lost their invite, or switched computers, etc. ) this link can still be wrapped around the image for easy visual appeal.

## Proposed solution

Take the data that the user enters into the sign up fields and display it to the screen. This allows the user to see what they have written as well makes it easier to update information since they can see if they need to. [rough sketch in Figma](https://www.figma.com/file/j2Y1TzJsdx8J0TyCHor6q7/OpCode-Profile?node-id=0%3A1)

## Potential alternative solutions

See the points on the slack invite.

**Comment by jeffsnff** [comment]
I would like to take this up myself as well.

**Comment by ksmacleod99** [comment]
@jeffsnff are you working on this? You claimed it, it’s yours :)

**Comment by jeffsnff** [comment]
I am actually! Thank you.
