### ISSUE TITLE
Resources page needs "Powered By Algolia"

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/front-end#1136]
# Bug Report
## What is the current behavior?
Currently, the page at https://operationcode.org/resources doesn't display a little note "Powered By Algolia". In order to continue using their service for free under their Open Source/Non Profit plan, we need to have this.

## What is the expected behavior?
The user should be able to see "Powered by Algolia" near the search bar

## What steps did you take to get this behavior?
Navigate to https://operationcode.org/resources and look around the search bar

### Operating System
N/A
### Browser
N/A
### Is This A Third-Party Issue?

N/A

**Comment by kylemh** [comment]
Let's put it here:

<img width="1254" alt="1rem underneath the input bar, but aligned to the right border" src="https://user-images.githubusercontent.com/9523719/85323623-30271200-b47d-11ea-9fe4-6ac4401bc8a1.png">

**Comment by aaron-suarez** [comment]
Thanks, y'all! The Algolia people like it!
