### ISSUE TITLE
Duplicate current registration form and move it to a new, public route

### ISSUE THREAD

**Issue by ksmacleod99** [OperationCode/front-end#1141]
# Feature request
We want to create a user survey that looks a lot like registration in the information it gathers. It will eventually be accessed via a slash command on Slack. 

## Proposed solution
- Duplicate current registration form 
- move it to a new, public route called “survey”

## Additional context
Related to operationcode-pybot issue #184 and backend issue #347

**Comment by kylemh** [comment]
Closing because we won't be doing the OAuth work.
