### ISSUE TITLE
Create new form on front-end to trigger user connection process 

### ISSUE THREAD

**Issue by ksmacleod99** [OperationCode/front-end#1142]
# Feature request
Create a new form to trigger user connection process between Slack and OC profiles

## Proposed solution
Create a new form to trigger user connection process between Slack and OC profiles

## Additional context
Related to backend issue #346

**Comment by ksmacleod99** [comment]
@kylemh in your mind, will this need a design?

**Comment by kylemh** [comment]
No. The form should have 4 inputs in two groupings.

Your OperationCode.org email and your Slack email

**Comment by Beissner** [comment]
What's the status on this issue? Are we waiting for backend issue #346 to be completed first?

**Comment by kylemh** [comment]
Closing because we won't be doing the OAuth work.
