### ISSUE TITLE
Text disappears when hovering over link on the About Us page.

### ISSUE THREAD

**Issue by JohnGoure** [OperationCode/front-end#1143]
# Bug Report
## What is the current behavior?
Using the Chrome 83 browser navigate to the About Us page, scroll down to the WHAT WE DO section and hover your mouse the We have a podcast link. The text for the WHAT WE DO section disappears.

## What is the expected behavior?
The text in the WHAT WE DO section, in the About us page, should remain and a tool tip should be provided.

## What steps did you take to get this behavior?
As above, navigate to the about us page, hover over the We have a podcast link in the WHAT WE DO section. The text doesn't disappear when the browser is in window mode.

### Operating System
Ubuntu 20.04
### Browser
Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by cbituin** [comment]
Attempted to replicate issue to determine if it spans OS/Browser version. Replication unsuccessful. 

Operating System
Windows 10 Pro

Browser
Version 84.0.4147.89 (Official Build) (64-bit)

**Comment by kylemh** [comment]
I may have accidentally fixed it. @JohnGoure can you confirm?

**Comment by LindaCBeall** [comment]
@JohnGoure: Did the bug get resolved, can we close it?

**Comment by kylemh** [comment]
Yes, sorry!
