### ISSUE TITLE
Users can register with just an empty space for a name

### ISSUE THREAD

**Issue by jeffsnff** [OperationCode/front-end#1145]
# Bug Report
## What is the current behavior?
When signing up for Operation Code, you can sign up without entering any characters but a space. ( I currently did this so my first and last name come back as " " << blank space )

## What is the expected behavior?
You should have to type in an actual name example John Doe.

## What steps did you take to get this behavior?
In the first and last name input boxes I just hit the space bar.

### Operating System
Windows

### Browser
Firefox

**Comment by justin-reeves** [comment]
Is this being worked on yet? I would like to tackle it if not.

**Comment by kylemh** [comment]
go for it
