### ISSUE TITLE
PII is stored in browser cookies

### ISSUE THREAD

**Issue by jeffsnff** [OperationCode/front-end#1146]
# Bug Report
## What is the current behavior?
Once logged in, a user's first name, last name, and zip code are being tracked in the browser cookie storage.

## What is the expected behavior?
Instead, wherever we need this info we should make an API request using the `getUserPromise` method. We only need to store the token in the cookie (for now - this, too, is changed eventually).

## What steps did you take to get this behavior?
I logged in, went to inspect element > storage > cookies for current web session.

**Comment by jmayergit** [comment]
> (for now - this, too, is changed eventually)

On a separate note, how will this eventually be changed?

Thank you

**Comment by kylemh** [comment]
@jmayergit we're currently in the process of throwing away our authentication system and instead solely leveraging Slack OAuth as a means for people to authenticate. We'll be leveraging Auth0 as a 3rd party service and our authentication will be HTTP only.

**Comment by ajpgross** [comment]
Any progress?
I'm still familiarizing myself with the stack but, I might also recommend cleaning up the /auth endpoints that return a user object, as those props are contained in the JWT.

**Comment by kylemh** [comment]
You'd have to do that in the back-end repo and wouldn't be long-lived given our above plans to leverage Slack as our means of authentication. That doesn't sound like a bad idea though! Just maybe not the best considering the circumstances. Your call!

**Comment by ajpgross** [comment]
Got it, thanks for the extra info. Agreed that it's not worth the effort, given the planned auth overhaul
