### ISSUE TITLE
Update more fields of a users profile

### ISSUE THREAD

**Issue by jeffsnff** [OperationCode/front-end#1147]
# Feature request
Currently, when a user goes to update their profile, they can not change, zip code, first name or last name. A user should be able to change these since people get married, divorced, change names, as well as move.

## Proposed solution
Add a few more text inputs that will allow a user to input a name / address change.

**Comment by chrismgonzalez** [comment]
I think I could probably tackle this one!

**Comment by jeffsnff** [comment]
@chrismgonzalez Do it man! If you need any help, let me know in Slack, and I can explain it better if need be.

**Comment by kylemh** [comment]
Closed in #1161
