### ISSUE TITLE
"Profile" nav item has "Donate" styles sometimes

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1163]
# Bug Report
## What is the current behavior?
Sometimes the "Profile" item in the nav bar has a blue background, like the "Donate" item. 

## What is the expected behavior?
The "Profile" item should never look like the "Donate" item.

## What steps did you take to get this behavior?
1. www.operationcode.org/login
2. login
3. notice that "Profile" is correct
4. reload
5. notice that "Profile" has styles meant for the "Donate" item.

**Comment by thecodestuff** [comment]
Hi Kylemh 
I can reproduce this issue , I like to work on this .

**Comment by kylemh** [comment]
@thecodestuff go for it!

**Comment by vatsalsharma376** [comment]
Is this issue fixed? I am not able to reproduce it.

**Comment by kylemh** [comment]
@vatsalsharma376 apologies -  you're right! I resolved this and forgot to close this.
