### ISSUE TITLE
OC Challenge Page: Make scrollable list for names added to page

### ISSUE THREAD

**Issue by sairina** [OperationCode/front-end#1176]
# Feature request
There are currently 50 names displayed on the [OC Challenge page](https://www.operationcode.org/challenge), but it would be beneficial if we had a scrollable list.

## Proposed solution
Make the current list of names on the page scrollable.

## Potential alternative solutions
Have columns, but they would still need to be scrollable.

**Comment by justin-reeves** [comment]
Would like to try and tackle this today if no one else is already working on it!

**Comment by kylemh** [comment]
@sairina were all the names not visible to you? The list doesn't appear to be truncated.

**Comment by sairina** [comment]
Hey @kylemh, it was a feature @aaron-suarez pointed out that could be improved for the future! I think currently, it's correct, but as more names are added, it may be nice to allow for scrolling instead of a long list.

**Comment by justin-reeves** [comment]
Will be working on this today to perform actions discussed in [Slack](https://operation-code.slack.com/archives/C04FASBU9/p1596141056203700) with @kylemh .

Plan is to create flexible columns to display a number of names per column with as many columns as can fit into max-width of the section.
