### ISSUE TITLE
Resources Page: prompt user to log in when upvoting/downvoting and submitting or editing a resource

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/front-end#1197]
# Feature request

The Resources page has an upvote/downvote feature. This only works when the user is logged in. The user should be prompted to log in or sign up when clicking it if they are not already logged in/signed up.

## Proposed solution

Please create a modal popup that has a login form to enter your username and password, as well as a link to the /join page in case they don't have an account. Optionally, it would be cool if there was a "forgot password" link right there in the modal as well.

Once you've logged in, it would be nice if it automatically did the upvote/downvote action you were trying to do when you were prompted to log in, but that's not necessary.

You'll want to use the Modal component and the LoginForm component in conjunction with eachother!

## Potential alternative solutions

Redirect to login page - this is inferior because you shouldn't have to leave the page and then figure out how to come back to the resource you're trying to upvote.

**Comment by datphotogurl** [comment]
I'm working on design needs on this issue today.

**Comment by datphotogurl** [comment]
![Login_PopUp](https://user-images.githubusercontent.com/51416206/91667279-5c8c8980-ead1-11ea-8f24-8da50c87ba6f.png)

**Comment by aaron-suarez** [comment]
Looks great! Thanks for this @datphotogurl

**Comment by BhuwanChandra** [comment]
@aaron-suarez Is anyone working on this? I would like to work on this issue.

**Comment by kylemh** [comment]
go for it!

**Comment by kylemh** [comment]
Up next @chynh wants to connect the upvote/downvote functionality. No issue will be made to protect against the Hacktoberfest swarm 😂
