### ISSUE TITLE
Resources page: form to upload a new resource

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/front-end#1198]
# Feature request

The API allows an authenticated user to upload a new resource or edit an existing one. This functionality should be available on the /resources page as well.

## Proposed solution

There should be a button that says "Add a new resource" or perhaps just "New Resource". When you click the button, if you're not logged in, you should get the same modal described in #1197. If you are logged in, you should see a form that allows you to upload a new resource. This can either be a dedicated page or an additional modal. We have a design for this floating around somewhere, and I'm hoping that makes it into this issue but I don't have it readily available right this moment.

## Potential alternative solutions

I don't have an alternative solution to a basic form to fill in the information. If you think of one, feel free to suggest it, but the form seems like the most natural solution.

## Additional context

I'm not sure if the edit resource button/form should go in this same issue or if that should be a dedicated issue. Please let me know if I need to create another one or describe above, in more detail, what that will look like.

**Comment by kylemh** [comment]
@aaron-suarez I know that Laura made us a modal for this, and spent a brief moment of time looking for it on Slack search. That would be valuable to put here.

**Comment by aaron-suarez** [comment]
Per slack discussion, we couldn't find the good mockup from Laura. But here is a really basic drawing that I did in about 5 minutes which has the relevant fields and basic shape of what the form might look like:

<img width="653" alt="Screen Shot 2020-01-27 at 2 38 32 PM" src="https://user-images.githubusercontent.com/2008701/91521965-a3eefc00-e8be-11ea-8361-d93428824c9c.png">

**Comment by TallanGroberg** [comment]
Hello, If no one is working on this I will start working on this issue.

**Comment by aaron-suarez** [comment]
@TallanGroberg please wait until we have #1197 complete. We need a way to prompt the user to log in before we provide the form to submit a resource

**Comment by datphotogurl** [comment]
![Upload Resource Modal](https://user-images.githubusercontent.com/51416206/91670761-61ac0180-eaee-11ea-99c4-b2daccd87535.png)

For exports of each individual graphic element needed, please contact me.

**Comment by TallanGroberg** [comment]
Ok, I'll start working on this. 

Should I get ahold of you on slack?

**Comment by aaron-suarez** [comment]
Yeah we can chat on slack or on here, it's up to you. I'm usually faster to respond on Slack, but I'll see it on GitHub as well

**Comment by datphotogurl** [comment]
@TallanGroberg if you need any of the graphic buttons/icons, hit me up on Slack (@CynK) and I'll send to you.

**Comment by TallanGroberg** [comment]
I'm making good progress on this issue, I just have to figure out how to verify if a user is logged on or not.

**Comment by aaron-suarez** [comment]
@TallanGroberg If you want, we can create an endpoint on the API that just simply checks if you have valid credentials with your request. It would return a 401 if you're not logged in, but a 200 if you are logged in, without making any changes to resources on the server. Right now, that type of endpoint doesn't exist.

For security reasons (XSS/CSRF mitigation), there is no way to view the cookie from JavaScript, so you can't check whether you have a session on the server. 

It's possible that the backend also sends some kind of data indicating that the user is logged in, but if that is happening today, I don't know what it is or how to look for it.

Other than querying the Resources API or checking for some token on the client, I'm not sure how you would know whether you're logged in. Perhaps @kylemh or @AllenAnthes has an idea. If not, I'll open an issue to make this "check if logged in" endpoint in the Resources API for you to be able to use for this purpose.

**Comment by TallanGroberg** [comment]
I think making an endpoint to check for would be the best idea. Maybe there is a better idea but that will get the job done.

**Comment by cynk** [comment]
Hello- can you all remove me from this thread? I think you have the wrong
cynk.

**Comment by kylemh** [comment]
Actually, the auth token and some other data is stored via cookies. We already do an `isLoggedIn` check in the Nav Bar (to conditionally render the `"Log Out"` option.

As Aaron noted, this isn't the safest practice, but I'm okay with you continuing knowing that once we resolve this vulnerability, it's still totally valid to reference a boolean cookie in the hopes of... eagerly assumptive logged in state. If the user isnt logged in, but incorrectly has the cookie, the server would respond negatively and we can then redirect the user to login.

@cynk I've edited the post that tagged you, you now simply need to unfollow the thread yourself. I can't control that for you, sorry!

**Comment by datphotogurl** [comment]
Sorry for the confusion all, I’m listed as @datphotogurl on Github since my Slack username was already taken.
