### ISSUE TITLE
Create a Resources Tab on Top Nav

### ISSUE THREAD

**Issue by datphotogurl** [OperationCode/front-end#1200]
**Feature Request**
Currently, the Resources page (https://www.operationcode.org/resources/1) is not public, and hard to find on the site unless someone searches on a search engine or knows the direct URL.

**Proposed Solution**
Proposed solution is to make "Resources" as it's own tab on the top nav.

**Potential Alternative Solutions**
Move "Resources" as a drop-down under "About Us" but this is not an ideal user action since "Resources" are high priority items on the site.

**Additional Context**
Resources API requires Login/Join to occur in order to save or submit new resources. 

Dependent issues: #1197 #1198 

Tags: Design/mock-ups needed

**Comment by datphotogurl** [comment]
![Upload Resource-Login-Join Link](https://user-images.githubusercontent.com/51416206/91670841-442b6780-eaef-11ea-8cb3-9b6b7275d6a0.png)

Suggested mock-up

**Comment by kylemh** [comment]
@LindaCBeall I think we should come up with a decision on what the top nav should look like. We dont need any designs, just an ordering of nav items and which ones have sub items.

I would suggest:

- **About Us** with **Contact Us**, **FAQ**, and **Podcast**
- **Who We Serve** with **Resources**, **Code Schools**, and **Events**
- **Get Involved** with **Sponsorship** and **Leadership Circle**
- **Login** (no sub-menu for this one - people would click login if they want to register)
- **Donate**

This change removes "Join" from the nav menu and then I'd add an extra button on the landing page hero so that it's Learn More + Join

What do you think?

**Comment by datphotogurl** [comment]
Adding @hollomancer here. So from a UX perspective, and some of the content is a little old/not updated like "Leadership Circle" - David R mentioned this probably needs to be renamed and updated, along with many other sections, including the Volunteer section way down on the FAQ page.  We can probably discuss this further in our 
Product Meeting. Regarding the Top Nav:

1. First Tab **About Us**: it would make sense if **Who We Serve** is on the same page as **About Us** as a section, and secondary drop-downs listed in order of priority content>Podcast>FAQ>Contact Us. The future **"Success Stories"** page would eventually exist in this first tab of drop-downs.
2. Second Tab would make sense to be **Resources** then **Code Schools** and **Community Events** (instead of just events, this page can show all the platforms we exist as sections named "Our Slack Community", then geographic locations for cleaned-up Chapters. Content clean-up needed soon on this page.)
3. The third tab "Get Involved" would make sense to have "Volunteer With Us". That page would have all the updated volunteer onboarding application information, followed by **Partnerships** (instead of the word Sponsorship which denotes negative connotations), then place Leadership Circle as unlisted until we can revamp this content to be more accessible to recurring monthly donors. New content suggestions: an "OC Alumni" where OC members who transitioned from newbie to the tech industry can sponsor a member (or several members) through an apprenticeship, mentorship or financial contribution.

**Comment by kylemh** [comment]
Sounds like there multiple issues we should make from this. The most important one would be how we put Who We Serve into the About page.

**Comment by adithyaakrishna** [comment]
@kylemh Can I work on this issue?

**Comment by kylemh** [comment]
You can work on any issue that is devoid of an assignee. I am assigned to this one.

**Comment by adithyaakrishna** [comment]
Okay 🚀

**Comment by diverheart** [comment]
Can I work on this issue?

**Comment by kylemh** [comment]
@diverheart You can work on any issue that is devoid of an assignee, but I am assigned to this one.

**Comment by kylemh** [comment]
resolved
