### ISSUE TITLE
Color for the Vercel Logo

### ISSUE THREAD

**Issue by AdiG06** [OperationCode/front-end#1204]
# Feature request

In the corporate sponsors section of the OC website, when we hover over the sponsors, all of the sponsors' logos gain color from the grey it was, except Vercel. The logo starts off as black, and does not have a transition to its true color.
## Proposed solution

Instead of the logo starting off black, I propose we have the logo start off grey, so when it is hovered over, it can transition to its true color of black.
## Additional context

![image](https://user-images.githubusercontent.com/69874317/92292183-b4136680-eed0-11ea-8417-f0e11800856a.png)
![image](https://user-images.githubusercontent.com/69874317/92292314-6814f180-eed1-11ea-8554-e62c0d9502be.png)

**Comment by kylemh** [comment]
Some of these are so thin, that if we start it off gray, then we'll have an inaccessible UI, as our color contrast ratio wont be WAI compliant.

I like your eye for polish though! Keep a look out for more stuff like this.
