### ISSUE TITLE
Add SlackView of #job-board to /jobs

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/front-end#1205]
# Feature request

[SlackView](https://slackview.app/) gives a public view of your slack channel to put on your webpage. According to their marketing page:
>SlackView provides a real-time stream of activity in slack channels of your choosing on your webpage. SlackView only has access to the contents of channels you explicitly invite it to, and you can remove the slack bot at any time.

Since our [jobs page](https://operationcode.org/jobs) is kind of basic right now with an indeed job feed that offers no real value (not to mention an outdated "featured job" that's impossible to keep up to date), we need to do something different. Our #job-board channel on slack is always up to date with great postings, often internships and opportunities at the companies our members work at. This is actually a _great_ call to action because people will post "DM me for more information" and stuff, which really showcases _why_ someone might want to join the slack team. We need to include in big letters "Join slack on operationcode.org/join to respond to threads" or something so prospective members know how to get in contact with posters of great opportunities.

## Proposed solution

I think my solution is actually in the problem statement. Stick the SlackView on the page.

## Potential alternative solutions

None.

## Additional context

Separately, we were lamenting about how terrible the job pages were, and we were raving about how cool it would be to add SlackView to one of our pages. We couldn't decide between #javascript and #career-advice and it wasn't entirely clear where it should go on the site. This solves multiple problems all at once!

**Comment by LindaCBeall** [comment]
I think this is a great idea! But it does show user's names, maybe privacy/security concerns?  I tested it on another workspace, I didn't see an option to make postings anonymous but maybe there's a way?  
<img width="681" alt="Screen Shot 2020-09-17 at 11 10 50 AM" src="https://user-images.githubusercontent.com/37910748/93511076-0f812380-f8d7-11ea-8114-4dfdb094dda6.png">

**Comment by aaron-suarez** [comment]
There are a few channels where people tend to post personal information or personal stories, but of all of them, I would think that #job-board would be the least likely. So if the only concern is their name, people should probably change their name to a different handle if they want to keep people from knowing it. Anyone can join our slack team, so it's not really a "private" space anyway.

That being said, maybe we should make an announcement in #general with an @ channel that let's people know that #job-board is going on the website and if they don't want their name displayed on the site, they should change their handle before posting in that channel.

**Comment by kylemh** [comment]
We could also have a bot DM people when they post or join in #job-board to let them know they're sacrificing privacy when they post an opportunity?

**Comment by LindaCBeall** [comment]
I like both. Sometimes people join, post, and then leave the channel - they will definitely see the message that way.

**Comment by Beissner** [comment]
Is anyone currently working on this?

**Comment by aaron-suarez** [comment]
@LindaCBeall Do you want to get with @Beissner and coordinate who's working on this? Now would be a great time to get it done 😄

**Comment by LindaCBeall** [comment]
@Beissner, I'll DM you on slack :)

**Comment by hollomancer** [comment]
Agree re. privacy concerns. Can names and avatars be filtered?

**Comment by kylemh** [comment]
Not within the iFrame.

I think the best route of action immediately would be to simply pin a message letting them know their job postings are not private, and - if they'd like them to be - to use the workflow.

Eventually, we could prevent messages from even being sent in the channel and ONLY allow posts via the workflow.

**Comment by LindaCBeall** [comment]
Can we just skip the 3rd party app all together and send to the website using the workflow/webhook?  We can pin a post encouraging people to use the workflow.

**Comment by kylemh** [comment]
That would be a lot of work with the Slack API, but it's possible.

**Comment by kylemh** [comment]
Canned cuz of privacy issues
