### ISSUE TITLE
Add the Secure Code Warrior logo to the front page.

### ISSUE THREAD

**Issue by Lianis-Operations** [OperationCode/front-end#1211]
# Feature request
To add Secure Code Warrior logo to the front page to ensure all our corporate partners/sponsors are placed on our public site.

## Proposed solution
Update the front page with the logo.

![scw_col_white_v_R_1000px](https://user-images.githubusercontent.com/51661129/92973323-3d540b80-f484-11ea-85dd-d202fc751cd9.png)

**Comment by datphotogurl** [comment]
Requesting a change to the original stated issue: please place the Secure Code Warrior logo to the following URL, under "Corporate Supporters": https://www.operationcode.org/sponsorship

**Comment by adithyaakrishna** [comment]
@kylemh Can I work on this issue?

**Comment by kylemh** [comment]
Unfortunately not! I can't give people s3 access.

**Comment by adithyaakrishna** [comment]
@kylemh  Can I Upload it as a png through assets/img/sponsors? and once the s3 storage has the image and if I get the URL then I'll change it to that.
or if you can upload the image to s3 bucket and then send me the image link, that would be good too I guess 😶

**Comment by adithyaakrishna** [comment]
This would be my First PR towards Hacktoberfest and after searching for like hours got one thing which I know of😶

**Comment by adithyaakrishna** [comment]
For now, I've made the site to fetch the URL from the image added above by @Lianis-Operations 
This is the SS of it,
![image](https://user-images.githubusercontent.com/23498248/94853136-8c201000-0448-11eb-8561-da57421add3b.png)

**Comment by kylemh** [comment]
Go for it! Just make sure the aspect ratio matches the others please.

**Comment by adithyaakrishna** [comment]
Thanks a lot 🚀
Yes, The Image container is handling the aspect of the image. Its being fetched from the URL of the Image added above by @Lianis-Operations
