### ISSUE TITLE
Add link to job in nav bar

### ISSUE THREAD

**Issue by AdiG06** [OperationCode/front-end#1225]
# Feature request

Right now, the only way to get to https://operationcode.org/jobs is to literally type it in, or scroll all the way down to the bottom of the page to find the link. 
## Proposed solution

Can we add a link to the jobs page in the nav bar?
## Potential alternative solutions

Instead of it having its own link, maybe we can also put it under Get Involved or any other appropriate groups
## Additional context

None.

**Comment by kylemh** [comment]
This is on purpose. It's not exactly as awesome page... If that changes with #1205 we can consider moving it!
