### ISSUE TITLE
Leverage cypress-testing-library in all Cypress tests

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1228]
# Feature request
We use a mixture of Cypress's 1st-class methods and [`cypress-testing-library`](https://github.com/testing-library/cypress-testing-library) methods to write our integration tests (located inside `./cypress/integration/`).

I'd like it if we ONLY used `cypress-testing-library` methods and if we never wait for requests to resolve (like [here](https://github.com/OperationCode/front-end/blob/main/cypress/integration/join.spec.js#L33)). Instead, trust the asynchronous nature of `cypress-testing-library` by using `findBy*` queries to assert for something to _eventually_ be true.

## Proposed solution
Use `cypress-testing-library` methods where able (see `resources.spec.js` and `code_schools.spec.js` for good examples).

**Comment by logesr** [comment]
@kylemh I can take this up!

**Comment by kylemh** [comment]
Have at it!
