### ISSUE TITLE
Allow aliased path imports in Cypress files

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1229]
# Feature request
To import code from other source files in Cypress files, we must import them with relative paths.

## Proposed solution
- Make it so that one can use alias paths for imports in the `cypress` folder.
- Convert relative path imports and make them point to the relevant alias.

**Comment by Ruchika30** [comment]
Can u pls explain a bit more @kylemh

**Comment by kylemh** [comment]
[Here's an article explaining path aliases](https://levelup.gitconnected.com/understand-and-configure-absolute-import-paths-in-javascript-5cde3be2630d). Let me know if this gives you enough context!

Essentially, path aliases are working in source code and in Jest code, but not in Cypress code.
