### ISSUE TITLE
UpgradeBrowserOverlay and Modal stories are broken

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1232]
# Bug Report
## What is the current behavior?
The following stories are broken due to a run-time error related to `gtag` being undefined (which makes sense cuz we dont ship google analytics to our Storybook).

- [UpgradeBrowserOverlay](https://storybook.operationcode.org/?path=/story/upgradebrowseroverlay--default)
- [Modal](https://storybook.operationcode.org/?path=/story/modal--default)

## What is the expected behavior?
The UI renders for both of these stories and does not care about `gtag`.

**Comment by tranlehaiquan** [comment]
@kylemh I created a pull to fix this. Please take a look, thank you :D.
