### ISSUE TITLE
ImageCard story's `children` control changes causes story to break

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1233]
# Bug Report
## What is the current behavior?
When viewing [the ImageCard story](https://storybook.operationcode.org/?path=/story/cards-imagecard--default) and making changes to the `children` prop on the "Controls" addon, the story has a run-time error.

## What is the expected behavior?
Storybook users should be able to adjust the `children` prop via the "Control" with any string.

**Comment by Tomekmularczyk** [comment]
@kylemh I believe it's because children are another component (<p>) and addon works only with a text. If I can find a fix, would you be fine with making children just a text in this story?
