### ISSUE TITLE
Upgrade Formik to v2

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1236]
# Feature request
We're using `formik@1^`. I wanna use `formik@2^`.

## Proposed solution
- Upgrade `formik` to the latest version 
- Convert implementations of formik to leverage `useFormik` hook instead of `connect()` or `<Formik>` render props.

**Comment by sravan7** [comment]
@kylemh 
I would like to work on it. Can you please assign it to me.

**Comment by kylemh** [comment]
We have a policy of not assigning issues to users not in our organization, to outwardly communicate that anybody is welcome to claim the issue. For context, we often dealt with people asking for assignment, but never returning. This accidental parking leads to extra maintenance work for maintainers.

Not to worry regarding Hacktoberfest though! I wont mark your fix as `spam` and GitHub cares about _opened_ pull requests, not merged ones.

**Comment by sravan7** [comment]
@kylemh 
can please give me a sample `console.log`. I tried lot it is not coming up. Even I removed `eslint`.
It is very difficult for me to debug without `console.logs`

**Comment by lakshyabatman** [comment]
Can you assign this issue to me?

**Comment by kylemh** [comment]
We have a policy of not assigning issues to users not in our organization, to outwardly communicate that anybody is welcome to claim the issue. For context, we often dealt with people asking for assignment, but never returning. This accidental parking leads to extra maintenance work for maintainers.

Not to worry regarding Hacktoberfest though! Assuming you face "competition", I will not mark your fix as `spam` - GitHub only cares about _opened_ pull requests, not merged ones.

**Comment by lakshyabatman** [comment]
I understand, thanks.

**Comment by Tomekmularczyk** [comment]
@lakshyabatman let me know in case you drop this, I would then like to take it

**Comment by lakshyabatman** [comment]
Yeah you can work on it. @Tomekmularczyk
