### ISSUE TITLE
Dont close the multi-select dropdown after an option has been selected

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1237]
# Feature request
As a user, I get very frustrated needing to click the multiple option dropdown after I choose an option. I'd like if the dropdown stayed open until I hit the `esc` or `enter` key, tab away from the input, or until I click outside of the element.

## Proposed solution
Ensure that the [Select](https://github.com/OperationCode/front-end/blob/main/components/Form/Select/Select.js) component doesn't close its list of options after choosing one (if `isMulti` is true).

## Additional context
It's [react-select](https://github.com/JedWatson/react-select) under the hood.

## Demo of issue
![demo](https://user-images.githubusercontent.com/9523719/94791811-00957900-038d-11eb-9647-29a6df1a37af.gif)

**Comment by murattishkul** [comment]
I'd like to work on this one, please kindly assign me to this issue)

**Comment by sravan7** [comment]
@kylemh 
I would like to work on it please assign it to me

**Comment by kylemh** [comment]
There's no need for assignment! I'll merge the best/fastest PR between anybody that contributes, but you'll still get credit during Hacktoberfest even if I don't merge your PR. ❤️
