### ISSUE TITLE
Navigate user to branding page if they right click the logo in our navigation bar

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1257]
# Feature request
When a user right clicks on the logo in the navigation bar, I want them to be navigated to the `/branding` page. Like [Sentry does](https://sentry.io/welcome/)

**Comment by cdterry87** [comment]
I would like to try this one, please :)

**Comment by kylemh** [comment]
Go for it!

**Comment by TheoGU** [comment]
I did a pull request 👀

**Comment by cdterry87** [comment]
@TheoGU no problem :)
