### ISSUE TITLE
Convert Formik render prop usages to leverage `useFormik`

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1272]
# Feature request
We use Formik via the render prop pattern, but I'd like for us to only use hooks.

## Additional context
- Guide for migrating from v1 to v2: https://formik.org/docs/migrating-v2
- More context provided via [this code review comment](https://github.com/OperationCode/front-end/pull/1262#pullrequestreview-501312218)

**Comment by A-Scratchy** [comment]
I'm happy to take this on if it's still up for grabs?

**Comment by kylemh** [comment]
go for it!
