### ISSUE TITLE
Footer links dont open when clicked on iOS mobile

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1277]
# Bug Report
## What is the current behavior?
Clicking any footer link does nothing.

## What is the expected behavior?
Clicking any footer link should navigate and scroll to the top of the navigated page.

## What steps did you take to get this behavior?
Used my iPhone and cried at the realization.

### Operating System
iOS 14

### Browser
Chrome iOS (uses the same rendering engine as Safari, so either should be the same)

**Comment by rzhekova** [comment]
I can give this one a try if that's ok

**Comment by kylemh** [comment]
Go for it

**Comment by rzhekova** [comment]
Hey @kylemh I think I've found the culprit, I'll send a PR over to you in a bit

**Comment by kylemh** [comment]
Closed in https://github.com/OperationCode/front-end/pull/1280
