### ISSUE TITLE
Web Page Unpublish: Leadership Circle

### ISSUE THREAD

**Issue by datphotogurl** [OperationCode/front-end#1295]
URL: https://operationcode.org/leadership_circle

**Requested Change**
This program is currently inactive. OC Executive Leadership asks that we un-publish this page until the program is revamped and ready to go live.

**Comment by cbituin** [comment]
@datphotogurl @kylemh Do we want placeholder text? Or just taking out the route completely?

**Comment by datphotogurl** [comment]
@cbituin Leadership wants to remove this page completely since we will be revamping the program. Is there a way to unpublish and not delete code?
