### ISSUE TITLE
Web Change: Podcast Page

### ISSUE THREAD

**Issue by datphotogurl** [OperationCode/front-end#1299]
# Feature request

**Proposed Solution**
Change Conrad Holloman to Conrad Hollomon (currently misspelled), and fix length of each podcast card to match the length of the card next to it (is there a more aesthetic way to ensure content and card length is more pleasing to the eye? Please feel free to suggest).

**Potential Alternative Solutions (see comments)**

**Comment by RollingThunderSagnik** [comment]
Hi! Can you please assign this to me?

**Comment by datphotogurl** [comment]
> Hi! Can you please assign this to me?

Hi @RollingThunderSagnik I cannot assign since I'm not an admin on the OC Github but I believe @calincionca35 may be taking this on. You two can collaborate if you want to tackle the card length issue.

**Comment by datphotogurl** [comment]
Other proposed solutions for the participant card lengths:

**Comment by datphotogurl** [comment]
**Other proposed solutions for the participant card lengths:**
Have the card length fixed and prevent a max amount of characters?
Right now there are two columns for the podcast cards (bios for each participant). The length of each card doesn't match each other and is really jarring to see from a design perspective. We can tackle this several ways: either limit the number of words in a card so the length is fixed (this solution would require editing existing content), create a scroll bar on each card to see more content. Another way is to place ellipses on the content that is too long with the words "view more" that is a hyperlink and that would take you to the actual podcast on that participant itself. You can decide which one is best is most user friendly.

**Comment by cbituin** [comment]
@datphotogurl I believe all the content is loaded dynamically from the actual podcast's rss feed.
