### ISSUE TITLE
Web Content Change: Landing Page [Success Stories] and New Feature Consideration

### ISSUE THREAD

**Issue by datphotogurl** [OperationCode/front-end#1329]
URL: https://operationcode.org/

### **Requested Change**
Please update the Success Stories featured members with the following content:
**Ali Cipolla-Taylor, Talent Acquisition at Microsoft**
_"I finished MSTA the last week of February, and then COVID hit. Employment was not going to happen…to anyone. I kept making calls, working on my skills, and throwing myself out there, and I got a role as a vendor at Microsoft. I’m half of the Data Privacy, Compliance, and Controls team for Talent Acquisition now. I had a lot of hard conversations with myself. I learned to lean into a support network, locally and online, through OpCode. I’m notoriously shy on the internet, but I knew that I couldn’t do this alone. Change happens when the discomfort of making the change is less than the life you’re living."_
![Ali_Taylor_Headshot](https://user-images.githubusercontent.com/51416206/95932499-01210d00-0d9a-11eb-96dd-eded4413a84c.jpg)

**Princeton Baker, Enterprise Security Analyst**
_"I am a Navy vet. I started at the US Navy Ceremonial Guard then to Norfolk to work on ship weapon systems to Miami then San Diego as a Corpsman. I struggled mentally when I first got out. I really had to dig deep and find who I am not what I think I am. I am not just a veteran or software developer or the annoying security guy. I think many veterans are looking for a title and a clear path. I found out quickly on this side of civilization you have to make your own path. I did a 16-week full time coding boot camp while full time in school with a wife and two young boys during quarantine. Right now I am an Enterprise Security Analyst for a payment company and I love it. It is my first role in tech."_
![Princeton_Baker_headshot](https://user-images.githubusercontent.com/51416206/95933132-b4d6cc80-0d9b-11eb-94c7-084048c8af3a.jpg)

**Jose Camilo, Full-Stack Developer**
_"I joined the Army in 2014 as an active duty Calvary Scout. In 2017, I left active duty to continue college and joined the Army Reserves as a Human Resources Specialist. Still serving in the Reserves now. I doubted myself a lot, wondering the type of role I should focus on, the type of tech/ tools I should learn. Starting courses that I would not finish, and starting projects that I would not finish. It sounds like I been training for 2 years to get to this point, but in reality, there were many occasions in which I did not code for weeks due to being overwhelmed and option paralysis. This was also around the time I discovered Operation Code. I am now a Full Stack Developer at UBS."_
![Jose_Camilo_Headshot](https://user-images.githubusercontent.com/51416206/95933959-bbfeda00-0d9d-11eb-80a6-81904a7c5df8.jpg)

##Please Submit Any New Feature Considerations in the Comments Below

**New Feature Request**
Non-time sensitive for this new feature, but meant to start a conversation about product needs. Landing Page Success Stories can ideally be linked to a new Success Stories page or the blog that @kylemh is currently working on. The Landing Page 3 Success Stories cards can be dynamic where a mouse hover can create a gallery change to new stories, or an arrow gallery scroll to new Success Stories. Tagging @LindaCBeall @Lianis-Operations @ksmacleod99 from Product Team to discuss. @jeckalmark for content and other feedback.

**Comment by kylemh** [comment]
@calincionca35 has a PR incoming for this 👍

**Comment by kylemh** [comment]
@datphotogurl I think https://github.com/OperationCode/front-end/pull/1331 covers most of what you wanted. I'm going to paste the content you described as "the non-time-sensitive feature" in #345 so that we can close this one.
