### ISSUE TITLE
Branding Page Updates

### ISSUE THREAD

**Issue by datphotogurl** [OperationCode/front-end#1357]
# Feature request
1. Currently, the https://operationcode.org/branding page is unlinked to the rest of the site. Please create a tab under "About Us" named "Branding Guide" where this page will be found.
2.The content also needs updating as the logos use the wrong HEX#s and are different than the set Branding Colors.
3.More clarification is also needed on when to use the various branding elements. There also needs to be new fonts for documents and graphics (and not just web fonts).

## Proposed solutions
1. Change the Title of this page to "Branding Guide". Add this language under the title: “For external organizations, corporate sponsors and press, please obtain specific guidance and approval from the Director of Communications prior to using Operation Code Branding on public platforms. You may email your request to marketing@operationcode.org”
2. Change the URL to the .eps file to an updated .eps file. (I cannot link .eps files here in Github, so please contact me to email you a copy.
3. Update the "Small" logo section with only the following updates: 
Rename the section "Small Logos". Change the guidance to, "For use when Operation Code's logo name is between 0-1 inch in height. In most cases, use the Original Small Logo. The Stacked Small Logo is to be used where graphics needs are larger in vertical height than horizontal width with the Operation Code logo name still under 1 inch in height.

Original Small
![Small_Original_Logo](https://user-images.githubusercontent.com/51416206/100491301-6d5c9380-30f0-11eb-8127-796a3bd1993f.png)

Stacked Small
![Small_Stacked_Original](https://user-images.githubusercontent.com/51416206/100491330-abf24e00-30f0-11eb-8f38-c7184e418dda.png)

4. Update the first "Stacked Logos" section with an updated guidance message and the following stacked logo names and stacked logos. Delete the second "Stacked Large Logos" section:

Use the Large Stacked Original logo in areas where you have more vertical space than horizontal. Only use the Red Stacked Logo for special holidays such as Thanksgiving, fall events, and Christmas. The Light Stacked Logo is to be used with dark or contrasting bright colored backgrounds.

Large Stacked Original
![Large Stacked Logo](https://user-images.githubusercontent.com/51416206/100491339-b876a680-30f0-11eb-875d-00b04e0951e1.png)

Red Stacked Logo
![Red Stacked Logo](https://user-images.githubusercontent.com/51416206/100491354-d217ee00-30f0-11eb-8a24-0010dc752809.png)

Light Stacked Logo
![Light Stacked Logo](https://user-images.githubusercontent.com/51416206/100491402-2327e200-30f1-11eb-96b2-7776b8964c69.png)
 
5. Update the "Medals" message to read: Use the following medals when you are prompted to upload a thumbnail logo only or profile photo. In most cases, use the OC Blue Medal. The Red Medal should only be used for holidays and special events (such as Thanksgiving, fall, or Christmas). The Navy Medal should be used memorandums or lighter bright colored backgrounds.

OC Blue Medal
![OC Blue Medal](https://user-images.githubusercontent.com/51416206/100491457-9b8ea300-30f1-11eb-87eb-7ca458dad5ea.png)

Red Medal
![Red Medal](https://user-images.githubusercontent.com/51416206/100491461-a1848400-30f1-11eb-966f-4765630ae22c.png)

Navy Medal
![Navy Medal](https://user-images.githubusercontent.com/51416206/100491473-c678f700-30f1-11eb-886b-79bfa589cc28.png)

6. Add a section named "Badges". The guidance to use badges are the following: You may also use badges as a profile photo or thumbnail. Badges should be used to accompany corporate sponsors or alliance partnerships on shared branding. Use the original OC Blue Badge in most cases, except the Red Badge for special events and holidays (Thanksgiving, fall and Christmas). The Navy Badge may be used with light backgrounds and bright colored backgrounds.

OC Blue Badge
![OC Blue Badge](https://user-images.githubusercontent.com/51416206/100491509-1061dd00-30f2-11eb-9d29-c90338cb0de4.png)

Red Badge
![Red Badge](https://user-images.githubusercontent.com/51416206/100491521-34bdb980-30f2-11eb-9e33-19d192d4f304.png)

Navy Badge
![Navy Badge](https://user-images.githubusercontent.com/51416206/100491534-3ab39a80-30f2-11eb-8991-559b7318b719.png)

7. Under the "Large" section, update this section with the name "Large Logos", with the following guidance:
Use the Original Large Logo in almost all cases above 1 inch in height. The Red Large Logo is to be used in special events (such as Thanksgiving, fall or Christmas), and the Light Large Logo is to be used with dark backgrounds or bright colored backgrounds.

Original Large Logo
![OC_Original_Large_Logo](https://user-images.githubusercontent.com/51416206/100491670-9599c180-30f3-11eb-9ba5-77f7ad07a3bb.png)

Red Large Logo
![OC_Red_Logo](https://user-images.githubusercontent.com/51416206/100491685-ac401880-30f3-11eb-839c-f40b7fb81eb9.png)

Light Large Logo
![OC_Light_Logo](https://user-images.githubusercontent.com/51416206/100491710-d5f93f80-30f3-11eb-8d93-172c8c7aeec1.png

8. Colors Section: Please add two sections. One named "Primary Color Palette". and "Secondary Color Palette".

Under the "Primary Color Palette", please create color cards with the following names and Hex # below:
OC Light Blue
HEX #3ED6F0
Navy
HEX #252E3E
Off-White
HEX #F7F7F7
Light Grey
HEX #CCCCCC
Black
HEX #000000

Under a subsection named "Secondary Color Palette", please create color cards with the following info:

OC Red
HEX #D1665A
Slate
HEX #3F566D
Dark Grey
HEX #666666

9. In the section titled "Fonts", please change this to "Typography". Add the following typography (in its sample font style) and guidance for each of the font types:

DIN CONDENSED BOLD - FOR USE IN HEADINGS, SUBHEADINGS, AND TITLES.
THIS IS A SAMPLE HEADER IN ALL CAPS.
COLOR IS HEX #3F566D - SLATE FOR LIGHT BACKGROUNDS.
HEADING FONT SIZE IS 32 PX.
ENCODE SANS - FOR WEB USE ONLY IN SUBTITLES AND SMALLER CARD TITLES. THIS FONT IS UNAVAILABLE FOR ADOBE, MICROSOFT OR GOOGLE DOCUMENTS.
THIS IS A SAMPLE SUBTITLE FONT IN ALL CAPS.
COLOR IS HEX #000000 - BLACK.
FONT SIZE IS 18 PX.

OPEN SANS BOLD - FOR USE IN SUBTITLES AND SMALLER CARD TITLES.
THIS IS A SAMPLE SUBTITLE FONT IN ALL CAPS.
COLOR IS HEX #000000 - BLACK.
FONT SIZE IS 18 PX.
USE THIS FONT IN MICROSOFT, ADOBE OR WEB
CONTENT WHEN ENCODE SANS IS NOT AVAILABLE
(ENCODE SANS IS ONLY AVAILABLE FOR
GOOGLE FONT PACKAGES).

Noto Serif, Medium. For use in paragraphs, body content, and other long quotes (italicize for quotes).
This is a sample body font in Sentence Case.
Color is HEX #666666 - Dark Grey.
Font size is 14 px.

10. Lastly, add a final guidance that reads, "View[ Operation Code's Storybook Component Library here](https://storybook.operationcode.org/?path=/story/heading--default)" 

## Additional context
This updated branding guidance, logos, primary and secondary color palettes and typography will assist press, partners and designers/front-end developers with clear and concise communications and serve as the official Operation Code Branding Guide.

**Comment by rufataliy** [comment]
Is this issue still ongoing?

**Comment by kylemh** [comment]
A pull request is open and ongoing.
