### ISSUE TITLE
Update History page

### ISSUE THREAD

**Issue by calincionca35** [OperationCode/front-end#1412]
# Feature request

Update OC's History page
## Proposed solution

Add OC's major milestones since 2017 to the History page
https://www.operationcode.org/history

**Comment by hollomancer** [comment]
Biggest thing will be VET-TEC, new board members

**Comment by calincionca35** [comment]
@hollomancer Would you also consider adding the GuideStar Gold Transparency Seal as a milestone?

**Comment by calincionca35** [comment]
My PR #1417 creates the placeholders for the copy for this issue.

**Comment by datphotogurl** [comment]
Here is the copy for the /history page. We will need to also create a tab under "About Us" in the head navigation (open another issue).

**### Operation Code’s History** 
**2011** - Operation Code's founder - retired U.S. Army Captain, David Molina, attended his first hackathon in New York City. After a weekend learning to code at [AngelHack](https://angelhack.com/), he was inspired to pursue software engineering as a post-military occupation. He submitted an application to The Flatiron School while on active-duty, only to discover that the program did not accept the "Post-9/11 GI Bill" as payment. 

**2013** - Molina exited military service and began to self-teach Ruby on Rails, a full-stack web development platform for building comprehensive web applications. He also started attending meetups with "[B-More on Rails](https://www.meetup.com/bmore-on-rails/)" while finishing [One Month's Rails](https://onemonth.com/) online course. After meeting Rubyists from around the world, he was introduced to the Portland, Oregon Ruby group. Inspired, Molina joined Techstars' [Patriot Boot Camp](https://patriotbootcamp.org/) (PBC) at George Washington University. 

During this time, Molina met with Virginia Senator Tim Kaine, to speak about the inability to use the Post 9/11 GI Bill for coding bootcamps. Before departing D.C., Molina received advice from U.S. Army Congressional Fellow Ben Culver, on gathering data to address the problem.  This was the beginning efforts for the current VET TEC pilot program under the Forever G.I. Bill.  

Molina’s next step was to purchase the domain opcod3.us and work with fellow Army veteran and software developer, Don Livanec to finish the first live webpage in 2013.

**2014** - At [Cascadia Ruby](http://cascadiarubyconf.com/),  Molina received encouragement from fellow Rubyist, Whitney Rose, to launch Operation Code's petition using "Launchrock". After lengthy discussions with Kristin Smith, Adam Enbar (representing The Flatiron School), and [Code Fellows](https://www.codefellows.org/), the first line of code was committed to [GitHub](https://github.com/OperationCode). Later that same year, web developer, teacher, entrepreneur and co-founder of [Code Fellows](https://www.codefellows.org/), Ivan Storck, purchased the domain 'operationcode.org' and became our first donor in the process.  To round out 2014, HackHands co-founders Forest Good and Geraldo Ramos joined Operation Code, designing our logo and providing veterans free access to [hack.summit](https://hacksummit.org/), a virtual conference to learn from the world's most renowned programmers.

**2015** - Operation Code formally launched as a nonprofit, led by David Molina. The kickoff event hosted dozens of veterans, software developers, media representatives, and staff members from Senator Ron Wyden and Congressman Earl Blumenauer's offices.

**April 2019** - As a direct result of the lobbying and work of Operation Code, [VET TEC](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/) was launched. Under the Harry W. Colmery Veterans Educational Assistance Act (also known as the Forever G.I. Bill), the [VET TEC](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/) program received $15 million per annual budget to assist students in the areas of: information science, software, computer programming, data processing and media application. This program does not utilize the entitlement and remaining months of the G.I. Bill, but requires candidates to have at least one day of remaining entitlement remaining. Students receive a housing stipend similar to the G.I. Bill at the E-5 with dependents rate.

**February 2021** - Operation Code receives the Gold Seal of Transparency from [Guidestar.org](https://www.guidestar.org/), the independent data analysis for non-profit certification of approval.

Today, Operation Code offers a supportive online community, local chapter meetups, mentorship, career networking, free learning resources, access to code school scholarships, and continues to advocate for veteran and military family access to code schools and careers in the tech industry.
