### ISSUE TITLE
Add "Intro to Slack" video on join page

### ISSUE THREAD

**Issue by Lianis-Operations** [OperationCode/front-end#1414]
# Feature request
Put https://youtu.be/m2JuAa6-ors on our website and link to it on the join page.

### Proposed solution

- Create a new page to house a Youtube video.
- The page should be titled: "Slack Guide" navigable via the `/slack_guide` path.
- It should use the Hero and Content components. [Component documentation here](https://storybook.operationcode.org).
- On the join page, at the end of the first paragraph put `Unfamiliar with Slack? Learn how to use it!` at the end. “Learn how to use it!” should be the content of a link.

**Comment by kylemh** [comment]
I feel like this should be included in the welcome email, and not the UI. Just a suggestion.

**Comment by calincionca35** [comment]
I suggest adding it to the UI so that it would **always** be available to **everybody**.

**Comment by calincionca35** [comment]
I suggest adding it to the UI so that it is **always** available to **everybody**.

**Comment by calincionca35** [comment]
I am interested in working on this issue.
