### ISSUE TITLE
Add copy to Donate page

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/front-end#1418]
# Feature request
Right now, the Donate page goes straight to the payment form. We'd like to add some copy, to give users context as to why they're donating, the impact that it has, that sort of thing.

## Proposed copy
TODO:

## Additional context
This may need a designer or a copywriter to look at.

**Comment by kylemh** [comment]
Once you get the copy, I'm sure @calincionca35 could knock this out in no time.
