### ISSUE TITLE
Slack Guide page FAQ content

### ISSUE THREAD

**Issue by calincionca35** [OperationCode/front-end#1420]
# Feature request

Provide FAQ content on Slack Guide page
## Proposed solution

Substitute FAQ placeholders w/ content on Slack Guide page

**Comment by aleforniadreamin** [comment]
Attach is the copy/content for the Slack Guide Page. A lot of new members may be using Slack for the first time so if we could provide these common questions/answers under the Slack Intro video it could provide a lot of value. 

[Operation Code Welcome Aboard.pdf](https://github.com/OperationCode/front-end/files/6224220/Operation.Code.Welcome.Aboard.pdf)

**Comment by calincionca35** [comment]
Thank you @aleforniadreamin for sharing this document.

**Comment by datphotogurl** [comment]
[Approved_Operation_Code_Welcome_Aboard .docx](https://github.com/OperationCode/front-end/files/6288674/Approved_Operation_Code_Welcome_Aboard.docx)

@calincionca35 Here is the updated and approved copy. I've placed the content in a Word doc for you to grab the screenshots and icons to place in the web format design. Thank you!
