### ISSUE TITLE
Add Operation Code's Threadless store to our website

### ISSUE THREAD

**Issue by datphotogurl** [OperationCode/front-end#1437]
**Feature request**
We have a Threadless shop for merchandise that needs larger exposure on our website.
 
**Proposed solution**
A proposed solution is to create a tab under "Services" on the top nav called "Merch Store" that will go to this link when clicked: https://operationcode.threadless.com/
<img width="1286" alt="Screen Shot 2021-04-26 at 3 56 09 PM" src="https://user-images.githubusercontent.com/51416206/116142579-0e537880-a6a8-11eb-9ef4-ae9cfb0ba848.png">

**Additional proposed solution**
On the  [Services page](https://operationcode.org/services), you can provide some additional copy or design segment that shows that we have a Merch Store:
<p>
Do you love Operation Code? Check out our [Merch Store](https://operationcode.threadless.com/) and get some swag!
</p>

**Comment by kylemh** [comment]
For whoever develops this:

The link's pathname can just be `/swag`

https://operationcode.org/swag

**Comment by RoseKimball** [comment]
Hi, I would like to work on this one.

**Comment by kylemh** [comment]
We don't reserve issues, but feel free to tackle it!
