### ISSUE TITLE
Add checkbox to signup flow for users to acknowledge they have read and agree to CoC

### ISSUE THREAD

**Issue by Lianis-Operations** [OperationCode/front-end#1481]
# Feature request
Add checkbox for the website to require that the Code of Conduct has been read and acknowledged.

## Proposed solution
Language next to checkbox:  "I have read and agree to Operation Code’s Code of Conduct.”

## Additional context
Link to CoC: https://github.com/OperationCode/operationcode_docs/blob/master/community/code_of_conduct.md

**Comment by kylemh** [comment]
PR open. Ideally, the integration tests fail because I didn't update them to account for the new checkbox. I'm gonna head to bed, and will update the tests at some point tomorrow and hear back from y'all on QA!
