### ISSUE TITLE
Update Sponsor Logo

### ISSUE THREAD

**Issue by datphotogurl** [OperationCode/front-end#1485]
# Update O'Reilly Logo

![ORM_logo_rgb](https://user-images.githubusercontent.com/51416206/134560130-20a5796a-1265-4132-bbaa-70c2812ae87e.png)

**Comment by kylemh** [comment]
Need to get my AWS account reset so I can update the image in S3, but consider this in-progress

**Comment by kylemh** [comment]
Sorted!

![Screen Shot 2021-09-23 at 3 34 21 PM](https://user-images.githubusercontent.com/9523719/134572167-c1b7be16-5f29-4b1f-99e8-00b2df3fc43a.png)
![Screen Shot 2021-09-23 at 3 34 23 PM](https://user-images.githubusercontent.com/9523719/134572168-c91c1955-8651-435d-a916-dd04f987e893.png)

**Comment by datphotogurl** [comment]
Thank you!

*Cynthia S. Kao,*
Founder and CEO,
*Reb**irth Media LLC*
+1(202)716-5860
https://ckaojohnson.wix.com/rebirthmedia

[image: https://www.instagram.com/datphotogurl/]
<https://www.instagram.com/datphotogurl/>

<https://www.linkedin.com/in/cynk/>

<https://twitter.com/datphotogurl>


*Thank you for supporting a Veteran-owned, minority-owned and woman-owned
small business!*


*Notice of Confidentiality:The information transmitted is intended only for
the person or entity to which it is addressed and may contain confidential
and/or privileged material. Any review re-transmission dissemination or
other use**of or taking of any action in reliance upon this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error please contact the sender immediately by return
electronic transmission and then immediately delete this transmission
including all attachments without copying distributing or disclosing same.*
