### ISSUE TITLE
Code Schools page has a small style bug

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1527]
# Bug Report
## What is the current behavior?
When visiting operationcode.org/code_schools and opening the US State dropdown, it can collide with badges on code school cards.

## What is the expected behavior?
The dropdown should always cover any UI below it.

### Screenshots
<img width="1004" alt="Screen Shot 2021-10-24 at 10 51 20 PM" src="https://user-images.githubusercontent.com/9523719/138627755-a74c82a1-4ef0-4b59-8c84-1bf2a0b86084.png">

**Comment by dlim87** [comment]
That other post seems to have been deleted, so I took a stab at it: https://github.com/OperationCode/front-end/pull/1529
