### ISSUE TITLE
Remove out-of-date information from README

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#16]
# Feature
## Why is this feature being added?

We don't want people being mislead. Only leave the absolute facts within the documentation.

I realize there's not much info here. The documentation is a bit on the back-burner for me since we're not really advertising this repo except internally. Ask questions in here or DM me on Slack if you'd like to help out.

**A prime example:** the readme includes commands from CRA + the old repo. You can quickly remove that information and put up the correct info just by reading `package.json`.

**Comment by chrismgonzalez** [comment]
I will tackle this one
