### ISSUE TITLE
Improve fidelity of logo by using svg

### ISSUE THREAD

**Issue by toadkicker** [OperationCode/front-end#1608]
Using SVG logo would help it look better on high resolution monitors. It is currently blurry on 4k displays.

**Comment by datphotogurl** [comment]
Here's the SVG for whoever wants to update this ticket.
![OC-Logo](https://user-images.githubusercontent.com/51416206/171261570-d5b649c9-d2bc-455a-b78a-588a7d3cff94.svg)
!

**Comment by madebanjo** [comment]
I will like to update the logo of the project with an svg logo. I hope it is still open to my contribution.

**Comment by jflem1** [comment]
Is updating to an svg logo still available?

**Comment by kylemh** [comment]
Yes
