### ISSUE TITLE
Limit width of page content to match width of nav bar

### ISSUE THREAD

**Issue by toadkicker** [OperationCode/front-end#1610]
For example, there is text well into the gutters of the branding page, and those gutters are not equal sizes.
<img width="1437" alt="Screen Shot 2022-05-31 at 10 41 36 AM" src="https://user-images.githubusercontent.com/523330/171248145-564136c0-91e3-4759-9413-caa476211140.png">

**Comment by kylemh** [comment]
No, I'm not sure what's being said. There exist dozens of pages where the nav width isn't the guide for gutters. Content spans past that width on many instances.

**Comment by toadkicker** [comment]
I think that is a bug not a requirement

**Comment by kylemh** [comment]
What I'm saying is this specific UI spans past the nav, but it also does on many pages because it's not related.

That doesn't mean we can't fix the UI. It also doesn't mean we can't fix only THIS UI.

I only had context that you were reporting these issues as a helpful bypasser. If @datphotogurl wants this UI changed in some way, I'll do so!

**Comment by datphotogurl** [comment]
I believe Todd was just making helpful suggestions. If the CSS width spans on all of the pages, could we fix that for all the pages?

**Comment by kylemh** [comment]
edited title and OP and reopened issue

**Comment by elite16op** [comment]
is this issue still available to work on ?

**Comment by kylemh** [comment]
Yes, but I don't think it will be a simple issue - just a heads up!

**Comment by recondesigns** [comment]
> Yes, but I don't think it will be a simple issue - just a heads up!

I see that the nav has a `max-width` of 1200px, but not seeing any other sections of content (or content) with that constraint. Are you thinking there would need to be changes for each page, or possibly even each section of content?

**Comment by kylemh** [comment]
The `Container` component (which is omnipresent) has a max-width of 1400px.

The difficulty in this ticket is that there are MANY components that have arbitrarily set max-widths. The solution won't be just changing `Container` and/or `Nav`.
