### ISSUE TITLE
Implement newly-designed /get_involved page

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#165]
# Feature
## Why is this feature being added?

Our design team has come up with a beautiful redesign to simplify UX.

## What should your feature do?
Implement the newly-designed landing page via `pages/get_involved.js`
Here is the mock-up: https://invis.io/GRO3FKUEZMX

**Comment by kylemh** [comment]
This is a request for a new or redesigned page.

- The page should be implemented by creating a file (or editing the file if it already exists) in the `pages` folder. The file name should match the route (ex: code_schools --> `pages/code_schools.js`).
- Please remember to leverage the `<OutboundLink>` component when dealing with external links (leaving our hostname - operationcode.org)
- Do your best to limit stylesheets imported into `pages/styles`. 
- Only modularize potentially reusable content via `components` - it's okay to implement everything in the page file and let us as staff members sort out where you could write for reuse (if anywhere).
- If no design is missing mobile-specific or desktop-specific styling, do your best to work with what's given. A good rule of thumb is that any lists displayed in rows on desktop mocks, can be displayed one-per-row on mobile.

**Comment by tigclaw** [comment]
Can I try tackling this one?

**Comment by ksmacleod99** [comment]
@tigclaw I assigned myself as a placeholder for you.
Let us know if you have questions!

**Comment by kylemh** [comment]
Closed in #214
