### ISSUE TITLE
Add New Board Members to the Team Page

### ISSUE THREAD

**Issue by datphotogurl** [OperationCode/front-end#1696]
# Feature request
Please add the following new board members to this page: [(https://operationcode.org/team)]

## Proposed solution
The following new Board members need to be added with their names, photos and bio's:

Conrad (Alex) Bituin 
![Bituin,Alex](https://user-images.githubusercontent.com/51416206/210856051-70c8d05b-9282-49de-9746-356382e07fb0.png)

Conrad “Alex” Bituin is currently a Software Engineer in the payments domain for a financial services organization, and currently also serves as the Operation Code Outreach Lead and Director of Digital Strategy. Throughout his 14-year career in the U.S. Army Reserves, Alex has also worked in the sales, health and fitness, retail, insurance, and education industries - most recently serving as a 6th grade teacher. He is passionate about education and professional development opportunities for the U.S. military community. Outside of supporting and advocating for our military community, Alex enjoys spending time with his spouse and two children, diving into data science and machine learning projects, football (American), and home brewing.

Alex P. Wu 
![Wu, A P _Headshot](https://user-images.githubusercontent.com/51416206/210855700-61832a09-e9f9-4041-8c52-8cc12610b77b.jpg)

Alex is a Marine Corps Veteran and currently works at Twilio as Counsel, Law Enforcement and National Security.  

He was previously a litigation associate at the law firm Cooley LLP and a vetting attorney on the Biden-Harris Transition Team.  Before becoming an attorney, Alex served as a Marine combat engineer platoon commander in Helmand Province, Afghanistan, and then as a reserve tank platoon commander, executive officer, and company commander in the States.  While a reservist, he worked in Washington, DC for an AAPI-advocacy non-profit and then as a staffer in the White House Office of Management and Administration and the White House Counsel's Office.

Alex earned his J.D. from Stanford Law School, B.A. in Sociology from the College of William and Mary, and currently lives in the San Francisco Bay Area with his wife and their two bulldogs.  He is originally from the D.C. area and is a long-suffering Washington Wizards fan.

Martin Espinosa
![Espinosa,Martin](https://user-images.githubusercontent.com/51416206/210871125-c6882715-c74f-46b7-9aa6-eca11b02891d.jpeg)

Martin has been Technology Executive for over 25 years and is currently the VP of Internal Audit and Chief Audit Executive (CAE) at Juniper Networks.  He has deep experience in finance, risk, compliance, governance, technology and process improvement with experience in security, software, hardware, semi-conductor, gaming and banking sectors with global multi-billion dollar companies.  Prior to joining Juniper, Martin has been Chief Audit Executive (CAE) at multiple technology companies such as Symantec, Polycom, Electronic Arts and Avago (now Broadcom).  He has also worked in finance operations prior to his internal audit roles and served as Chief Compliance Officer for Polycom.  Other companies he has worked for include Sun Microsystems and Yahoo!!  He is a firm believer of mentoring, giving back to the community and working with others to grow.  He is a proud father of two and believes without work life balance you have no balance.  He earned his BA in Economics from the University of Dallas and his MBA from the University of Colorado. 

 Mike Roberts
![Roberts,Mike](https://user-images.githubusercontent.com/51416206/211065506-ff3e33f6-1fd3-4125-9336-09e073986a87.jpg)

Mike Roberts is a software engineer by trade with over three decades of experience programming. He is the founder and CEO of Creating Coding Careers, which helps underrepresented people break into tech and helps companies build high-performance engineering teams out of historically excluded tech talent. Having launched hundreds of new collar careers, he has grads working at IBM/RedHat, Apple, WalmartLabs, Sony, AWS, Facebook, Deloitte, Trust&Will, BD, NewRocket, and many more amazing tech companies.

**Comment by kylemh** [comment]
I'll have this sorted Monday

**Comment by animatefire** [comment]
I see this issue isn't closed yet. Mind if I tackle it?

**Comment by datphotogurl** [comment]
@animatefire yes, please go ahead and take this ticket!

**Comment by kylemh** [comment]
Sorry about the delay, Cynthia. I can definitely tackle this within 24 hours.
