### ISSUE TITLE
Reimplement /code_schools page

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#170]
# Feature
## Why is this feature being added?

https://operationcode.org/code_schools exists and it needs to exist in the new code base as well.

## What should your feature do?
- Implement the code_schools page via `pages/code_schools.js`
- Emulate [this mock](https://projects.invisionapp.com/share/KSO12EFRU7E#/screens/323736695_OC_Coding_Schools_Landing_Page).
- [See live source code.](https://github.com/OperationCode/operationcode_frontend/tree/master/src/scenes/home/codeSchools) Feel free to copy-paste a lot.
- Refactor as required to match our new standards (linting, using components where possible, etc.)
- Implement new card design
- Reference moocs from API ([see here](https://github.com/OperationCode/operationcode_backend/pull/250))

**Comment by kylemh** [comment]
This is a request for a new or redesigned page.

- The page should be implemented by creating a file (or editing the file if it already exists) in the `pages` folder. The file name should match the route (ex: code_schools --> `pages/code_schools.js`).
- Please remember to leverage the `<OutboundLink>` component when dealing with external links (leaving our hostname - operationcode.org)
- Do your best to limit stylesheets imported into `pages/styles`. 
- Only modularize potentially reusable content via `components` - it's okay to implement everything in the page file and let us as staff members sort out where you could write for reuse (if anywhere).
- If no design is missing mobile-specific or desktop-specific styling, do your best to work with what's given. A good rule of thumb is that any lists displayed in rows on desktop mocks, can be displayed one-per-row on mobile.

**Comment by kylemh** [comment]
Please note: https://github.com/OperationCode/front-end/issues/225

**Comment by markchernov** [comment]
I'd like to start working on this story. It looks like https://operationcodeapi.docs.apiary.io/#reference/0/codeschool-collection/list-all-codeschool-members?console=1   returns invalid json response. Validation result could be seen at https://jsonlint.com/

**Comment by markchernov** [comment]
Is there a way to add additional schools of different types to that mock endpoint?

**Comment by kylemh** [comment]
@markchernov are you on Slack?

We can chat about this issue in more detail there. I wouldn't be setting you up for success in letting you work on this issue just yet, as I don't have good enough reqs laid out.

We can chat through them and relay that info here, but this issue is a large amount of work.

**Comment by markchernov** [comment]
Page Design at: 
https://projects.invisionapp.com/share/KSO12EFRU7E#/screens/323736695_OC_Coding_Schools_Landing_Page

**Comment by markchernov** [comment]
@kylemh none of the Mooc schools are coming back from API now. Is the Mooc json shape is going to be the same as other schools? If yes, why even separate them to special section? I could just add filter to show Moocs

**Comment by kylemh** [comment]
Great question

MOOCs are hard-coded for now

I think there's an `is_mooc` value that will come from the code schools - that may already be in, but just hardcode an array of objects representing `moocs`
