### ISSUE TITLE
Reimplement /press page

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#171]
# Feature
## Why is this feature being added?

https://operationcode.org/press exists and it needs to exist in the new code base as well.

## What should your feature do?
- Implement the page via `pages/press.js`
- [See live source code.](https://github.com/OperationCode/operationcode_frontend/tree/master/src/scenes/home/press) Feel free to copy-paste a lot.
- Refactor as required to match our new standards (linting, using components where possible, etc.)
- Add new content not on site! A list of news articles under a section titled "In The News". Put every article listed in these issues in the list: [one](https://github.com/OperationCode/operationcode_frontend/issues/1017), [two](https://github.com/OperationCode/operationcode_frontend/issues/1016), and [three](https://github.com/OperationCode/operationcode_frontend/issues/1015).

**Comment by kylemh** [comment]
This is a request for a new or redesigned page.

- The page should be implemented by creating a file (or editing the file if it already exists) in the `pages` folder. The file name should match the route (ex: code_schools --> `pages/code_schools.js`).
- Please remember to leverage the `<OutboundLink>` component when dealing with external links (leaving our hostname - operationcode.org)
- Do your best to limit stylesheets imported into `pages/styles`. 
- Only modularize potentially reusable content via `components` - it's okay to implement everything in the page file and let us as staff members sort out where you could write for reuse (if anywhere).
- If no design is missing mobile-specific or desktop-specific styling, do your best to work with what's given. A good rule of thumb is that any lists displayed in rows on desktop mocks, can be displayed one-per-row on mobile.

**Comment by dirtyredz** [comment]
My Pr should not close this issue, its only a copy of the live site. No new content has been added.

**Comment by dirtyredz** [comment]
Do we have a new design template? So i can look into tweaking styles and more specifically where were looking at adding the above referenced media articles.
I don't want do a bunch of styling work if there is already a planned redesign available.

**Comment by kylemh** [comment]
There's no mock to speak of here.

**Some of the style issues I noticed, if you'd like to tackle them:**
- Videos aren't centered horizontally
- Videos and Branding sections should have a `theme` prop value of "grayLight"
- Photos aren't within a flex container / centered horizontally
- The CivixX OutboundLink should have a `hasIcon` prop value of "false"

**Comment by dirtyredz** [comment]
The horizontal centering doesn't look terribly off but notice it the most on lower device sizes. Ill see what can be done for those. The other issue look fairly straight forward.
Ill work on these tonight, Thanks

**Comment by dirtyredz** [comment]
I understand, i figured it was a matter of browser or device that was causing the distinct difference.
Your screenshot helps me identify what you were seeing, and I should have that fixed with my next pr.

**Comment by kylemh** [comment]
Chrome@latest for what it's worth

**Comment by dirtyredz** [comment]
This latest PR should close out this issue. A few merge conflicts need to get fixed but doesn't look like anything major.

**Comment by kylemh** [comment]
Assigning myself as a placeholder for @dirtyredz
