### ISSUE TITLE
Sitemap and sitemap generation is broken

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1719]
# Bug Report
## What is the current behavior?
![Screenshot 2023-09-05 at 10 36 28 PM](https://github.com/OperationCode/front-end/assets/9523719/2dae019c-ef25-45eb-9e03-57ab8403b516)

## What is the expected behavior?
There should be no errors on operationcode.org/sitemap.xml according to Google's Sitemap validator.

**Comment by kylemh** [comment]
I was trying to use https://tagparrot.com/ and noticed the issue

**Comment by AndrewLester** [comment]
I'd be happy to take this on given its high priority. Let me know if that's okay, and I can self-assign!

**Comment by kylemh** [comment]
Of course! Have at it. Check out https://github.com/iamvishnusankar/next-sitemap
