### ISSUE TITLE
Integrate Tailwind

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1724]
No need to replace old styles yet, but we want to use Tailwind. So, integrate Tailwind and map our current CSS variables to relevant CSS properties.

**Comment by subhajit20** [comment]
@kylemh  hey, can I integrate tailwind css?

**Comment by MehdiDgrs** [comment]
Hey I would like to contribute

**Comment by kylemh** [comment]
Hey y'all! I didn't realize the request would be so popular 😂 

Maybe since @subhajit20 asked first? Go for it!

**Comment by subhajit20** [comment]
@kylemh  Hey one more question, Which one is the gloabl.css file on this project I did not find any global.css.
 is that named differently?

**Comment by kylemh** [comment]
https://github.com/OperationCode/front-end/tree/main/common/styles

**Comment by subhajit20** [comment]
@kylemh  after runnig f`yarn lint:styles` command

this following is comming:

common/styles/globalStyles.css
 4:1  ✖  Unexpected unknown at-rule "@tailwind"  at-rule-no-unknown

 5:1  ✖  Unexpected unknown at-rule "@tailwind"  at-rule-no-unknown

 6:1  ✖  Unexpected unknown at-rule "@tailwind"

**Comment by subhajit20** [comment]
@kylemh made a pr.
Please check and let me know for further corrections.
