### ISSUE TITLE
Replace Jest with Vitest

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1727]
I want the unit tests to run faster

**Comment by Surya-V-28** [comment]
@kylemh  is it for beginner ? or some one working on this ? I wanna  love to

**Comment by kylemh** [comment]
Go for it!

**Comment by Tushar2930** [comment]
Hey, I am looking forward to work on this issue. Can you explain a bit more ?

**Comment by kylemh** [comment]
Whoops! Critical typo in the title. Hopefully what I want is more obvious now?

Here's this as well: https://vitest.dev/guide/migration.html

**Comment by Tushar2930** [comment]
can I work on this now?

**Comment by Surya-V-28** [comment]
yes , sure, i am not sure how to solve , please assign this to tushar,

**Comment by collabroski** [comment]
I'm new. How do I start on this? Have brain will travel.
