### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by subhajit20** [OperationCode/front-end#1730]
# Bug Report
## What is the expected behavior?
Twitter logo is updated recently and hasnt been updated on the site

### Screenshots
![Operation Code _ Home - Google Chrome 12-09-2023 22_22_39](https://github.com/OperationCode/front-end/assets/99127578/74218682-4102-4920-9987-aa16dbc2f824)

**Comment by kylemh** [comment]
I purposefully don't want to update 😂

**Comment by JustinKSU** [comment]
I agree with you.
