### ISSUE TITLE
Create login and registration flows

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#174]
# Feature
## What should your feature do?
- Create routes at `/login`, `/sign_up`, and `/join`.
- Create a modal-focused login flow
- Redesign and simplify current registration flow
- Add section for [data use info](https://github.com/OperationCode/operationcode_frontend/issues/983)
- Collaborate with @Wimsy113 and @lauraux to ensure design/product vision is being executed properly.
- Be aware of the discussion [here](https://github.com/OperationCode/operationcode_frontend/issues/877) and [here](https://github.com/OperationCode/operationcode_frontend/issues/867) and [here](https://github.com/OperationCode/operationcode_frontend/issues/754) and [here](https://github.com/OperationCode/operationcode_frontend/issues/410) and [here](https://github.com/OperationCode/operationcode_frontend/issues/409)

**Comment by wimo7083** [comment]
Also, please include me (for backend things) as we wish to hook certain actions up on a completed registration. Right now we don't have a singular event we can tie to this completed registration and this leads to not knowing exactly when a user is done. 

Most likely this will include some minor BE work on changing the api, but I'll make sure that gets done.
