### ISSUE TITLE
CypressError when run "model.spec.js" test file

### ISSUE THREAD

**Issue by Albert98L** [OperationCode/front-end#1747]
# Bug Report
## In your IDE terminal run  `yarn test:e2e`
- Click on "E2E Testing" from the Cypress window
- Choose a Chrome browser
- Click on "Start E2E Testing in Chrome"
- Click on "model.spec.js" test file 

### Screenshots
<
![Screenshot 2023-10-03 113431](https://github.com/OperationCode/front-end/assets/122150791/62cc90f7-1bdd-4bac-a217-0c0f0c17a808)
![Screenshot 2023-10-03 113437](https://github.com/OperationCode/front-end/assets/122150791/da37f2e5-5c7e-490c-aff5-be13297234b1)
>

**Comment by kylemh** [comment]
Hey! We actually run the integration tests as part of CI and they're all passing so this must be a setup error or a Cypress bug. Either way, I'm going to close the issue.

**Comment by Albert98L** [comment]
@kylemh  Thanks for the feedback, generally it is a bug or not

**Comment by Albert98L** [comment]
@kylemh In addition, we have this message "The following error originated from your test code, not from Cypress."

**Comment by kylemh** [comment]
The tests work on my machine and they work in CI. If you figure out a fix, feel free to submit a PR!

**Comment by kylemh** [comment]
Ah, I think I figured it out and committed a fix for ya: https://github.com/OperationCode/front-end/commit/f24c0ff3d99b5e852bdaf234ebc9a7c351ea7ed8
