### ISSUE TITLE
Add ability to rate code schools

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#176]
# Feature
## Blocked
#174 
#175 
#170 

## Why is this feature being added?

We previously discussed adding alumni to the code schools page and ability for them to add code school reviews.

## What should your feature do?
- Allow registered users to validate their status as a particular code school alumni
- Allow those users to vote on said school's performance non-anonymously
- Implement UI that allows for rating and reviews to be displayed per code school.

**Comment by hollomancer** [comment]
Closing this for now - anonymous rating of code schools gets us into Course Report / Switchup territory and we won't have the capacity to do that just yet.
