### ISSUE TITLE
Client-side routing is broken in local development

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#177]
# Bug Report
## Mitigation
To continue working, simply reload the route you navigate to.

## What is the current behavior?
When switching routes in local development via `next` `Link` components, following error is displayed:
![screen shot 2018-10-01 at 2 03 02 am](https://user-images.githubusercontent.com/9523719/46279522-2679b000-c51e-11e8-87b7-6175fdd9b0d8.png)

## What is the expected behavior?
Routing occurs normally

## What steps did you take to get this behavior?
Run local dev server, click "About" in header, and then click "History" in header.

### Operating System
MacOS Mojave@latest

### Browser
Chrome@latest

### Is This A Third-Party Issue?

Maybe?
https://github.com/zeit/next.js/issues/5291
https://github.com/zeit/next-plugins/issues/282

### Important Note
This doesn't have a noticeable affect on prod. I believe every route ends up being SSR (not ideal), but at least the user wont notice any issues.

**Comment by popugang** [comment]
Same problem

**Comment by kylemh** [comment]
There is an advertised work-around that does not seem to work for us (importing an empty stylesheet). This isn't a helpful comment, but it does mean that we're not blocked on this issue...

Just that it's really hard. 😓

**Comment by sethbergman** [comment]
The custom server I've been working on has seemed to remedy this. I'll try to get the issue and PR in as soon as I can. Hopefully it will kill two birds with one stone. :bird: :bird: :gem:

**Comment by kylemh** [comment]
Interesting 🤔 

I'm worried about the implications there. Is HMR still viable?

I ended up spending some side time on this and found the following info:
https://github.com/zeit/next-plugins/issues/273
https://github.com/akiran/react-slick/issues/842#issuecomment-385378629

Summarized theory: Perhaps because we're messing with custom fonts, Mini-Extract-CSS plugin needs to be aware of those a lá file-loader (like in the 2nd link). I wasn't able to experiment on the theory, but it does seem that the projects which have issues with client-side routing AND don't work with the empty `_app.js` stylesheet import ALL seem to fuck with fonts.

**Comment by sethbergman** [comment]
I looked further into this and realized that I was running the build first, then `yarn start` which I modified to be `node server` in `package.json`. So looking back on this issue, I don't think it addresses the issue with HMR. The good news is that it works perfectly and doesn't have any routing issues. It loads much faster than `next start`, even if you run the build process first. There's a lot of issues reported in the next.js repo on similar findings, so it's correct to presume that it's a third party issue.

**Comment by kylemh** [comment]
Ah. To be clear, nothing is breaking with next start or any builds. The error above is found when you use yarn dev

Also, even though nothing breaks in prod, this issue does affect the website negatively - note that every page is SSR. Client side routing never takes over.

**Comment by kylemh** [comment]
🤔 while connecting our CSS variables to fonts, I broke stuff, but noticed client-side routing began working again. I am wondering how closely tied our usage of `@font-face` is to this problem.

**Comment by AmanAgarwal041** [comment]
you can checkout a fix for the client side css fix https://github.com/AmanAgarwal041/next-css-fix

**Comment by kylemh** [comment]
Waiting on Next to resolve this issue.
