### ISSUE TITLE
New Page: Scholarships Program

### ISSUE THREAD

**Issue by datphotogurl** [OperationCode/front-end#1817]
# Add Scholarships Program Page
Please add Scholarships Program as a dropdown option under the Services tab. Proposed URL: [(https://operationcode.org/scholarships/)]

## Proposed Design
[https://xd.adobe.com/view/b1c7ca5c-1253-4dd5-acb4-004b98660d84-e494/]
![Web 1920 – Scholarships Program Page](https://github.com/OperationCode/front-end/assets/51416206/8e1f7e0f-e06d-4fdf-bd18-08a89226f3b5)

## Proposed Solution
Each "card block" will show the description of each of our scholarship platforms. **With the exception of the first bloack for Code Platoon**, please allow each of the other blocks to be clickable to the main Scholarship form URL here: [(https://airtable.com/appeXPiUS5GQwC7Vi/shr5CuF4IJGks7Wfp)]

**Code Platoon x Operation Code's scholarship block will need to link to a separate page. See the below section on Code Platoon. Separate issue to be linked here. (Separate issue: [https://github.com/OperationCode/front-end/issues/1818)]**

## Hero Image
![Scholarships-Hero-Web](https://github.com/OperationCode/front-end/assets/51416206/dcb7bd6c-1736-4526-a56c-4afc4ef38e0a)

## Content
Description under title:

Our Scholarships Program is a competitive benefit that contributes directly to the professional development
And career growth of our service members, Veterans and military family members. 
To qualify, you must be an active member of our Operation Code community ([join here](https://operationcode.org/join)), 
a U.S. active duty,  Reserves or National Guard military service member, Veteran or military dependent. 
You must also abide by the [Operation Code Scholarships Policy](https://docs.google.com/document/d/1KsdkKB1RyEuI7tBspuabxqJ-7n_PhL3B4vdHkBp_-7U/edit?usp=sharing).
 We provide learning licenses and access to the below platforms: 

1. **Code Platoon X Operation Code**
![Code-Platoon-Primary Logo](https://github.com/OperationCode/front-end/assets/51416206/b95ccc58-e2dc-4b64-850d-30c69334168f)

Apply to attend a full ride
scholarship to one of the
Code Platoon’s coding bootcamp
cohorts

2. **Coursera - Google Certifications**
![Google](https://github.com/OperationCode/front-end/assets/51416206/61cc07af-de85-4d0d-b463-30bac9e6fac8)
![coursera-logo-full-rgb](https://github.com/OperationCode/front-end/assets/51416206/d823e6cd-3bb3-42d3-b245-7764cd5a460c)

Get certified with Google and
prepare for in-demand jobs
in Cybersecurity, Digital
Marketing & Analytics,
Data Analytics, IT Support,
Project Management, & UX Design.

3. **CompTIA Certifications Training & Exam**
![CompTIA-Large_Logo](https://github.com/OperationCode/front-end/assets/51416206/1a78b12a-5535-441a-942c-ee627f1aca6a)

With more than 2 million IT
certifications issued worldwide,
CompTIA is dedicated to helping IT
professionals lead the charge
in our digitally connected world.

4. **Secure Code Warrior**
![Secure-Code-Warrior](https://github.com/OperationCode/front-end/assets/51416206/bc3ad588-a144-4258-8a93-81841650333b)

Are you interested in using one
of our licenses with
Secure Code Warrior?
Sign up today and beef up your
appsec skills while gaming!

5. **Treehouse**
![treehouse-logo-duotone_treehouse-logo-combo-duotone-large (1) (1)](https://github.com/OperationCode/front-end/assets/51416206/5d6dc454-0863-4ead-8d46-bb6b608593de)

Start your journey into coding, 
programming, and design.
Perfect for beginners,
intermediate
and advanced learners.

6. **Udemy**
![udemy-logo-red](https://github.com/OperationCode/front-end/assets/51416206/ca977330-4540-4e5c-862f-d0fbca9e2af8)

Skill up to success! Udemy offers
over 185,000 courses and has
49 million students. Learn
programming, marketing,
data science and more.

**Comment by vazquezea96** [comment]
Id like to tackle this assignment!

**Comment by datphotogurl** [comment]
Go ahead @vazquezea96, lemme know if you need any help!

**Comment by vazquezea96** [comment]
Copy that, thank you!
