### ISSUE TITLE
Hero banner text minor styling issue

### ISSUE THREAD

**Issue by michaelDragomir** [OperationCode/front-end#1821]
# Bug Report
## What is the current behavior?

no margins when in the small viewport range..
![Screenshot 2024-06-04 at 12 46 04 PM](https://github.com/OperationCode/front-end/assets/129689060/3cd7185e-cef9-4cfd-9350-baead77ca46e)

## What is the expected behavior?
Should have padding around the text.

## What steps did you take to get this behavior?
added padding

**Comment by kylemh** [comment]
#1822
