### ISSUE TITLE
Add EIN to footer

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/front-end#226]
# Feature
## Why is this feature being added?
Organizations need our EIN in order to donate to us.
## What should your feature do?
Add our EIN to the footer. Text should be "Copyright 2018 Operation Code™. Operation Code is a 501(c)(3) nonprofit, EIN 47-4247572."

**Comment by kylemh** [comment]
Closing to prevent multiple forking efforts. Referenced in #219
