### ISSUE TITLE
Favicon path issue

### ISSUE THREAD

**Issue by sethbergman** [OperationCode/front-end#232]
# Bug Report
## What is the current behavior?
Favicon not rendering due to  `/` missing here:
https://github.com/OperationCode/front-end/blob/c109421080514e57621e81b338e1a874144e8ab1/components/head.js#L17
## What is the expected behavior?
Favicon renders as expected
## What steps did you take to get this behavior?
Build and start

**Comment by kylemh** [comment]
![screen shot 2018-10-17 at 3 47 17 pm](https://user-images.githubusercontent.com/9523719/47120549-f3286800-d223-11e8-832e-6743b7eef739.png)
this doesn't appear to be an issue on prod

**Comment by sethbergman** [comment]
> this doesn't appear to be an issue on prod

That's because there are tons of references to the favicon in the `components/head.js` file.

**Comment by kylemh** [comment]
I'm confused. There's a single reference to favicon. It's on line 30 of the file you mentioned.

**Comment by sethbergman** [comment]
I think I'm the one that got confused here. You mentioned a favicon issue in slack, and I assumed that this was what you were referencing. My fault.
