### ISSUE TITLE
Create an automated project board

### ISSUE THREAD

**Issue by sethbergman** [OperationCode/front-end#237]
# Feature
## Why is this feature being added?
GitHub now has templates for automated project boards. I'm opening this issue to discuss the details. I have used the template *Automated Kanban with Reviews* and I recommend it for this project.

## What should your feature do?
Automate moving issues and pull requests based on their status. Reminds those assigned to PR reviews.

**Comment by wimo7083** [comment]
This is something we'd probably do across multiple projects, could you give us some images of what this would look like and what this would help us with?

Does this help with assigning individuals who aren't in our organization?

**Comment by sethbergman** [comment]
I'm not sure about the last question, but the best way to test drive it is to add one to your own repository. Once you add the *Automated Kanban* or *Automated Kanban with Reviews*, there are some introductory cards that explain the possibilities better than I could.

**Comment by kylemh** [comment]
@dmarchante is thinking about Waffle.io
I know you use ZenHub locally

If we're really reaching the point where tracking issues is difficult, I'll prioritize it, but let's reserve the repository's issues page for issues with the actual codebase.

Bring up any organizational or managerial aspects in #oc-projects - it'll always be a good discussion. We're always adapting!

**Comment by sethbergman** [comment]
Just to clarify, it doesn't change the way that issues and PR's. It's in the Projects tab. Here's some information about it. I personally don't have a preference whether it's implemented or not. It's just a common thing for agile teams to have. :smiley: 
https://help.github.com/articles/about-automation-for-project-boards/#automation-options
