### ISSUE TITLE
Allow user to edit account from /profile

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/front-end#239]
# Modify User information
## Why is this feature being added?

We need to provide a way for users to modify their 
## What should your feature do?

[controller file](https://github.com/OperationCode/operationcode_backend/blob/73a5861cf672a644879bc347023f7622c2c16900/app/controllers/api/v1/users_controller.rb#L25)

The apiary shows that the only things a user can currently modify are, which is how the front-end is setup. 
[api-link](https://github.com/OperationCode/operationcode_backend/blob/73a5861cf672a644879bc347023f7622c2c16900/apiary.apib#L1816)

```ruby
    education_level: "College Graduate" ,
    mentor: "true",
    scholarship_info: "true",
    employment_status: "Employed",
    company_name: "Comcast",
    company_role: "Developer",
    military_status: "spouse",
    volunteer: "false",
    branch_of_service: "Air Force",
    interests: "Python, Python, Python, Python"
```
But the actual endpoint shows that more params are allowed

[allowed](https://github.com/OperationCode/operationcode_backend/blob/73a5861cf672a644879bc347023f7622c2c16900/app/controllers/api/v1/users_controller.rb#L54)

```ruby
:email,
:zip,
:password,
:mentor,
:first_name,
:last_name,
:bio,
:verified,
:state,
:address1,
:address2,
:username,
:volunteer,
:branch_of_service,
:years_of_service,
:pay_grade,
:military_occupational_specialty,
:github,
:twitter,
:linked_in,
:employment_status,
:education,
:military_status,
:company_role,
:company_name,
:education_level,
:scholarship_info,
:role_id,
interests: []
```

Some of these attributes should probably be included in the user information update. 

As we use email as the primary key, I think all but that should be allowed for now. 

Additionally we should eventually allow a user to delete their account if we wish to stay in compliance with future data regulations. 

Let's use this issue to discuss the problem.

**Comment by kylemh** [comment]
No longer blocked by UI, since login/registration is viable.
