### ISSUE TITLE
Link to Github Workflow is broken/returns 404 error

### ISSUE THREAD

**Issue by chrismgonzalez** [OperationCode/front-end#24]
# Bug Report
Link to "Github Workflow" in Readme.MD returns a 404 error
## What is the current behavior?
Clicking on link returns 404
## What is the expected behavior?
Clicking on link leads user to the right content
### Operating System
Windows 10 64-bit
### Browser
Chrome 67

**Comment by chrismgonzalez** [comment]
I can copy/paste the workflow into the Readme from the current front end repo.

**Comment by chrismgonzalez** [comment]
I can work on this one - I will port over what is in the current contributing.md to reflect the new dev workflow with new repo URL and new yarn storybook commands.

Give me the go ahead and I will tackle it.

**Comment by kylemh** [comment]
Dupe #16 - I'll leave the issue open as a means of focusing sub-tasks.

**Comment by chrismgonzalez** [comment]
This issue should be resolved once `CONTRIBUTING.md` is built out.

**Comment by kylemh** [comment]
Looks like this got closed by your work 👍
