### ISSUE TITLE
Change Link for V School

### ISSUE THREAD

**Issue by kaciej** [OperationCode/front-end#240]
# Feature
## Why is this feature being added?
V School has added a section of their website specifically for veterans.

## What should your feature do?
I just need the link for the code school, V School changed from https://vschool.io/contact/  to https://vschool.io/veterans/

**Comment by RaevLogic** [comment]
I can take care of that.

**Comment by GrootKo** [comment]
can i take this issue if it not done by @RaevLogic

**Comment by RaevLogic** [comment]
Sorry, I should have mentioned this earlier. This particular issue is actually a back-end problem, specifically one that admin needs to take care of. The correct person on the team has been notified of the issue.

**Comment by wimo7083** [comment]
This is taken care of . Had to use the admin dashboard.

**Comment by wimo7083** [comment]
![image](https://user-images.githubusercontent.com/10781353/47606042-d29ea180-d9cb-11e8-9849-357fa1a3c18e.png)
