### ISSUE TITLE
Allow more options on 'Which describes you' during sign-in.

### ISSUE THREAD

**Issue by Litodude** [OperationCode/front-end#246]
# Feature 
More drop-down Options during New User sign-up

## Why is this feature being added?
To find out the military background of the individuals joining our organization, or lack there of. 
## What should your feature do?
It should have these options:
1.Prior-Military / Veteran
2. Active-duty Military
3. Guard/Reserve Military
4. Mil-family/Mil-Spouse
5. Kickass Civilian

_Check all that apply_

##What does this influence?
We should be able to pull up better user analytics based on microsegmented data from our users on initial sign-up.

**Comment by Litodude** [comment]
OP update with more info

**Comment by kylemh** [comment]
I'm gonna kick this to wont-do...

@Litodude lets confer after I've implemented the new registration flow, yes?

I advise watching #174 and hitting me up after!
