### ISSUE TITLE
Add meta tag to ErrorDisplay component

### ISSUE THREAD

**Issue by sethbergman** [OperationCode/front-end#252]
# Feature for SEO

## Why is this feature being added?

Adds the following meta tag to `components/ErrorDispaly/ErrorDisplay.js` for SEO purposes:
```
<meta name="robots" content="noindex, nofollow"/>
```

Tells Google and other search engines not to index any dead links.

## What should your feature do?
Adds a rule for robots, specifically search engine crawlers to not index or follow any links to pages that don't have a status of 200.

**Comment by kylemh** [comment]
You can use the Next.js `<Head />`  component for this 👍
