### ISSUE TITLE
Create /donate page

### ISSUE THREAD

**Issue by Litodude** [OperationCode/front-end#269]
# Feature
Create operationcode.org/donate URL

## Why is this feature being added?
URL that's shorter and easier for us to advertise and link on marketing literature.

The current 'Donate' button on OC frontpage links to (https://secure.lglforms.com/form_engine/s/BRtP7QUKyHOyEYsZROsRew) The url is really long, and not appealing as a donate button. 
## What should your feature do?
Instead of implementing a custom form, a URL pointer to the existing link (https://secure.lglforms.com/form_engine/s/BRtP7QUKyHOyEYsZROsRew) for collecting donations.

**Comment by kylemh** [comment]
@TomerPacific I'd hold off until we get some more reqs.

In reality, I believe we plan on creating a `/donate` page.

@Litodude if you'd like a more shareable donate link, consider using `short.cm` (on our Slack that'd be `/shorted https://long-donate-url.com`

**Comment by kylemh** [comment]
@dmarchante how copy

**Comment by kylemh** [comment]
Blocked by needing a mock.

Gonna get info from David really quick and paste it here...

**Comment by kylemh** [comment]
Gonna close this for now, as the board is really happy with sticking to LGL foe the foreseeable future.
