### ISSUE TITLE
Integrate PostCSS Media Variables

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#295]
# Feature request
**Is your feature request related to a problem? Please describe.**
The problems outlined in #292 are unsolvable without this PostCSS plugin.

**Describe the solution you'd like**
Integrate https://github.com/WolfgangKluge/postcss-media-variables and prove it works in a pull request with one example integrated.

**Additional context**
This blocks #292

`postcss.config.js` will need to look like:
```javascript
/* eslint-disable global-require */
module.exports = ({ file, options, env }) => {
  const ENV = env.toLowerCase(); // eslint-disable-line no-unused-vars

  return {
    ...options,
    plugins: [
      require('postcss-media-variables')(),
      require('postcss-import')({ root: file.dirname }),
      require('autoprefixer')(),
      require('postcss-media-variables')(),
    ],
  };
};
```

**Comment by nryoung** [comment]
@kylemh if there are no objections, I will go ahead and snag this one.
