### ISSUE TITLE
Create mobile navbar

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#303]
# Feature request
**Is your feature request related to a problem? Please describe.**
The desktop version of the navbar is done and dusted. We now need a simpler version of the navbar that renders for tablets and mobile devices (using the relevant Redux state variables to conditionally render based upon that fact).

This issue is somewhat sparse, as I gave @jmayergit instructions over the phone.

**Additional context**
See #17

**Comment by mattbyrnes** [comment]
I'm picking up this issue.

**Comment by kylemh** [comment]
As noted on Slack, this issue is assigned to @jmayergit  👍
