### ISSUE TITLE
Change Partners to Sponsors

### ISSUE THREAD

**Issue by AshTemp** [OperationCode/front-end#309]
# Bug Report
## What is the current behavior?
On the current home page sponsors are listed as partners.

## What is the expected behavior?
Page says sponsors instead.

## What steps did you take to get this behavior?
Opened the home page.
![image](https://user-images.githubusercontent.com/19790104/49244786-9a311f80-f3de-11e8-8c41-8bb1bf1bc168.png)

**Comment by kylemh** [comment]
Just change [this](https://github.com/OperationCode/front-end/blob/master/pages/index.js#L115) to "Sponsors" 😁

**Comment by ivanmartinezmorales** [comment]
Created pull request for this issue.
