### ISSUE TITLE
Add "PostCSS Usage" section to CONTRIBUTING of repository

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#347]
# Feature request
**Is your feature request related to a problem? Please describe.**
It's always difficult to balance this repository in terms of being a safe haven for new developers to contribute, but also writing things in a maintainable and scalable fashion. Our CSS is rife with advanced features, mostly due to PostCSS plugins.

**Describe the solution you'd like**
I'd like to document all the ways our CSS is advanced and how they can and should leverage those advanced features in the README. The documentation should include tidbits on:

- Why we don't need vendor prefixes (autoprefixer)
- Why we shouldn't be writing custom media queries (postcss-custom-media)
- How and when to leverage CSS variables (see `variables.css` in `common/styles` folder)

**Comment by ksmacleod99** [comment]
If you have time to help catch me up a little this afternoon, I can tackle this.
