### ISSUE TITLE
Create BadgeGroup component and refactor pages with mapped Badge

### ISSUE THREAD

**Issue by juliantrueflynn** [OperationCode/front-end#375]
# Feature request

A number of times in the UI there's a row of Badge components and flexbox styles added. This doesn't follow DRY principle, and this could be refactored to be less redundant with a BadgeGroup component.

**Describe the solution you'd like**

Create BadgeGroup component with flexbox styles and tests. Then refactor any places in UI to use new component.

**Comment by kylemh** [comment]
Resolved in #383
