### ISSUE TITLE
Create /podcast page

### ISSUE THREAD

**Issue by jack-robs** [OperationCode/front-end#426]
Per request by our podcast leader, BobP, get a link to the podcast page on the OC website.

Intent: 
-increase traffic to OC podcast page
-highlight success stories of OC members interviewed 
-expand and link our network of content offerings for OC
https://operationcode.libsyn.com/website

Future work:
-build podcast page organic to OC's FE

- [x] Create `/podcast` page with HTML @danielasannino
- [x] Implement styles for podcast page - cards and images @danielasannino
- [x] Integrate podcast player widget on page @inbetweenwebdesigns
- [x] Create Cypress visual regression diff test
- [x] Link `/podcast` page on `/about` and `/who_we_serve` at a location of your discretion using the `<Link>` component.

- [ ] Change error content
- [x] Consider different dependency for react audio player
- [x] Update FAQItem and related components

**Comment by kylemh** [comment]
Would love BobP's input on content.

Here are some examples for design to emulate:
https://changelog.com/podcast
https://syntax.fm/
https://frontendhappyhour.com/

**Comment by VirgilHilts** [comment]
Thanks! I hate to make things overly simple, but I think this guy has the right idea: KISS.

https://medium.com/@JamesCridland/how-to-link-to-your-podcast-most-effectively-e15ecb1e1105

Don't add links to all the apps. Don't include all the episodes. Just have two big play buttons: one or Android & one for Apple.

Goal: two clicks and no decisions before you're actually listening to the latest episode:

1) the "podcast" link on the main page
2) the Play button.

**Comment by kylemh** [comment]
@LindaCBeall see above!

**Comment by VirgilHilts** [comment]
One more thing you might not think of at first: metrics!

What can/should we remember about people who come to the Podcast page?

1)  Were they on a mobile phone, or a desk browser? Details, e.g. Android / iOS?
  (maybe we already have this on the site metrics?)

2) Did they hit Play, or not?
  (we can do experiments on page design to see if they influence the # who hit Play)

**Comment by kylemh** [comment]
We will be tracking that all automatically :)

**Comment by kylemh** [comment]
Closed in #531
