### ISSUE TITLE
Integrate Sentry

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#430]
# Feature request
We want to know when our users see errors, and Sentry is a surefire way to get that.

**Describe the solution you'd like**
Integrate Sentry as described [here](https://github.com/zeit/next.js/tree/canary/examples/with-sentry).

**Comment by juliantrueflynn** [comment]
@rmkubik Kyle just assigned me in Slack just because of high priority. Let me know if you already started.

**Comment by kylemh** [comment]
Just reached out to Ryan, and he's good to go. You're all clear.
