### ISSUE TITLE
Code Schools field not resetting to initial state after clearing

### ISSUE THREAD

**Issue by juliantrueflynn** [OperationCode/front-end#437]
# Bug Report
## What is the current behavior?

On the page `/code_schools` there's a select field that filters cards by US state. After selecting a state, if the user then clears the field, the results do not return to initial state (showing all cards).

Field uses `react-select`, and you can of course ask me here or in Slack if you have any questions.

## What is the expected behavior?

After clearing the select field either through clicking the "X" or by backspace, the results show all cards again.

## What steps did you take to get this behavior?

1. Visit `/code_schools` page.
2. Select state from "Schools" field.
3. Clear field by pressing "X" or backspace button.

### Screenshots

![Showing empty results after clearing field](https://user-images.githubusercontent.com/2691129/56629577-d8dca600-661b-11e9-83d3-a79b644e0a54.png)

**Comment by tfquirk** [comment]
@juliantrueflynn @kylemh - I can work on creating a PR for this bug.

**Comment by juliantrueflynn** [comment]
@tfquirk Okay, great. Let me know if you have any questions here or on Slack. We're hoping for quick turn around time on this, let me know if that's an issue.
