### ISSUE TITLE
Create pagination component

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#447]
# Feature request
**Is your feature request related to a problem? Please describe.**
We will eventually be creating a page for our resources API. In preparation, we can accomplish some work ahead of time before the API is ready to go.

**Describe the solution you'd like**
Create a pagination component to navigate multiple pages of results.

Here is the mock:
![Screen Shot 2019-04-27 at 9 33 10 PM](https://user-images.githubusercontent.com/9523719/56858728-126f2300-6934-11e9-9a85-0f630743443d.png)

**Adjustment**: Instead of coloring the active page blue, please wrap it in the same blue as a square border (for accessibility concerns).

**Note**:
I highly recommend building the component using Storybook as a work-bench and keeping track of the following edge cases:

- Not having arrows when one page exists
- Not having a left arrow visible when on page one
- Not having the right arrow visible when on the last of all possible pages
- Only displaying 9 numbers at a time (what happens when your active page is 15 of 30?)

**Comment by kylemh** [comment]
Kevin asked to be unassigned so he can take a vacation before he starts his kick-ass new job!

I'm going to close his work-in-progress pull request, and open this issue back up to the public. Note that some good work was already ongoing:
https://github.com/OperationCode/front-end/pull/500/files

**Comment by michaelGerstner** [comment]
I can make this.

**Comment by juliantrueflynn** [comment]
Cool, go for it @michaelGerstner. I will assign myself to show this is taken.

**Comment by juliantrueflynn** [comment]
@michaelGerstner Just following up to see if you are having any issues I could maybe help with. Typically we like to give ~2 weeks, which is approaching, before changing assignment to someone else unless it's being worked on.

**Comment by juliantrueflynn** [comment]
@michaelGerstner Since I haven't heard back or seen any activity I'm going to take the assignment off myself and leave this open to anyone else to try. Let me know if you want to take another crack at it.

**Comment by IAMOTZ** [comment]
I would like to work on this issue.

**Comment by kencollier3** [comment]
Ok so this also looks like it's gone stale. Want me to look at this too @kylemh ?

**Comment by kylemh** [comment]
@kencollier3 this one needs to get done ASAP - feel free to snag, but we're not reserving things anymore ❤️

**Comment by kencollier3** [comment]
Fair enough.

**Comment by brittanyjoiner15** [comment]
I would love to help with this! But I’m quite a newbie and only familiar with HTML/CSS at the moment.

So I am assuming a it’s kinda like a mini nav bar structure? 

I’ll take a look at storybook!

**Comment by kylemh** [comment]
You know how you make a google search and page numbers show up below where each link goes to the next page? You’re just defining the UI for that.

If you’d like to setup some time, we could maybe meet next week to start off the work with paired programming. Just slack me.

**Comment by brittanyjoiner15** [comment]
Yeah let's do that - i'll slack you.

**Comment by chynh** [comment]
@kylemh is this issue still up for grabs or is it already been taken care of?

**Comment by kylemh** [comment]
A PR for it exists, so I’d look elsewhere.
