### ISSUE TITLE
Create ResourceCard component

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#448]
# Feature request
## Problem
We will eventually be creating a page for our resources API. In preparation, we can accomplish some work ahead of time before the API is ready to go.

## Solution
Create a ResourceCard component to showcase a resource item. It should use the exiting Card component and exist within `components/Cards`.

### Mock
![Screen Shot 2019-04-27 at 9 41 40 PM](https://user-images.githubusercontent.com/9523719/56858822-83fba100-6935-11e9-951b-13be22e94c34.png)

### Expected Data Shape For Component
resource -> object.required
resource.name -> string.required
resource.imageSource -> string.required
resource.description -> string
resource.upvotes -> number
resource.downvotes -> number
resource.href -> string.required

**Note**:
I highly recommend building the component using Storybook as a work-bench and keeping track of the following edge cases:

- Use ellipsis if the resource name or description is too long
- Thumbs for upvotes/downvotes should be lower opacity if their count is 0

**Comment by bdJohnson72** [comment]
I would like to take this one as part of the Front End incubator.

**Comment by gagandeepp** [comment]
assign this to me

**Comment by kylemh** [comment]
We can’t assign non-members. Also, we don’t reserve issues anymore. There’s a PR open for this already! Make sure you use it as a guide.
