### ISSUE TITLE
Improve form submission user experience

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#521]
# Feature request
When submitting the login and registration forms, as well as each step in the profile update form, we've used Formik's `setSubmitting` as a way to manage the state of the submit button being disabled or not. It seems, however, that the button will undisable _before_ the post-submit route transitions start, giving an opportunity for multiple submissions.

I'd like for it to stay disabled until the server responds _AND_ until the route changes.

## Proposed solution
None

## Additional context
Feel free to discuss here since there isn't a crystal clear acceptance criteria.

**Comment by RanadeepPolavarapu** [comment]
I can tackle this.

**Comment by kylemh** [comment]
what do u have in mind!?

**Comment by saf94** [comment]
Hey guys, is anybody working on this? If not i'd love to pick this up, i've looked into it a bit and may have some ideas

**Comment by RanadeepPolavarapu** [comment]
@saf94 I am currently looking into it.

**Comment by kylemh** [comment]
No worries about reserving anything! If you wanna take a whack, take a whack.
