### ISSUE TITLE
Integrate Cloudinary with <Image> component

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#523]
# Feature request
We don't want to manually generate multiple asset types to serve next-gen image formats to the right browser. For that reason, and many others discussed with Operation Code leadership, we'd like to integrate [Cloudinary](https://cloudinary.com/) for all our image purposes.

## Proposed solution
Integrate [Cloudinary](https://cloudinary.com/) to manage images (plug-in to `<Image>` component)

## Blocked
By #522

**Comment by kylemh** [comment]
Unblocked by #691

**Comment by hydrosquall** [comment]
Hi @kylemh , does Operation Code already have a Cloudinary account? 

It looks like the following subtasks could come from this issue, based on the React-SDK docs for Cloudinary: https://cloudinary.com/documentation/react_integration

- a `cloudName` for the account which hosts cloudinary's pictures
- Something in the build step for this project which uploads the contents of the `/static/images` folder to Cloudinary: https://github.com/OperationCode/front-end/tree/master/static/images
- A sweep of the current code to replace all references to the `https://operation-code-assets.s3.us-east-2.amazonaws.com/`  based images with links to the corresponding files in the Cloudinary account once that's created

**Comment by kylemh** [comment]
No account yet because we haven’t heard back about non-profit pricing. Lemme bother again this week and come back to you.

**Comment by kylemh** [comment]
I doubt this will ever get done since they won't respond to my non-profit requests 😭
