### ISSUE TITLE
Add a progress indicator to profile update form

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#527]
# Feature request
There are 3 mandatory steps to the profile update form and 1 that's conditionally rendered. Users are navigated to this form after registering, and it'd be very helpful and better for bounce-rates to give a progress indicator on the user's progress within that form.

## Proposed solution
Design and implement a progress indicator at the top of the update profile form view. I suggest adding it as an aspect of `MultiStepForm`.

**Comment by IAMOTZ** [comment]
Hi @kylemh 
I would like to claim this issue

**Comment by kylemh** [comment]
We're no longer dealing with claiming issues, so feel free to tackle it without attempting to reserve it!

**Comment by IAMOTZ** [comment]
Hi @kylemh 
I was able to prepare something, please check it out and let me know what you think: 

The form with a progress indicator bar and a text stating how much of the form is completed and how much is left:
![Screen Shot 2019-08-05 at 12 23 28 PM](https://user-images.githubusercontent.com/26048536/62461445-b7439c80-b77c-11e9-903b-d23a640287d2.png)  

Assuming one part of the form is already filled, notice the progress indicator bar changes and the text is also updated:
![Screen Shot 2019-08-05 at 12 26 32 PM](https://user-images.githubusercontent.com/26048536/62461484-e1955a00-b77c-11e9-9a22-5fddea2f57c3.png)

The form in the same state as the second image above, however, the progress indicator bar has a different color(I kinda prefer this):
![Screen Shot 2019-08-05 at 12 27 09 PM](https://user-images.githubusercontent.com/26048536/62461576-24efc880-b77d-11e9-83bd-b0763b7addf6.png)

**Comment by kylemh** [comment]
Just waiting on @Wimsy113 to provide feedback. 

For the code: however you implement this, I'd prefer it not to have too tight of an integration with the MultiStepForm component. If it does, I'd prefer it be a render prop at most.

**Comment by pranshuchittora** [comment]
I have implemented a stepper from in my recent project. [click here to view](https://srmmun.in/register/photo)
What about implementing something like it ??

**Comment by kylemh** [comment]
I'd prefer something close to what @IAMOTZ designed.

The only differences from his design I'd like to see:
- The progress bar itself is underneath the header (as opposed to above the button(s)).
- The text for the progress bar exists above the bar, centered horizontally.
