### ISSUE TITLE
Bug: Replace USMC with Army in success story section

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/front-end#574]
# Bug Report
## What is the current behavior?
Success story section is marked SEAN MCBRIDE, USMC, SOFTWARE ENGINEER

## What is the expected behavior?
Success story section is marked SEAN MCBRIDE, ARMY, SOFTWARE ENGINEER

front-end/common/constants/successStories.js

**Comment by kylemh** [comment]
Resolved

![Screen Shot 2019-06-10 at 12 14 03 AM](https://user-images.githubusercontent.com/9523719/59178722-ac6de200-8b14-11e9-88e7-bff421ea34bf.png)
