### ISSUE TITLE
Remove target="_blank" from all anchor tags where href starts with "mailto:"

### ISSUE THREAD

**Issue by AshTemp** [OperationCode/front-end#578]
# Bug Report
## What is the current behavior?
Clicking on the Find out How button on start your own meetup opens a blank page.
![image](https://user-images.githubusercontent.com/19790104/59165836-ed073480-8aef-11e9-8b0c-bc7c6b2e9d27.png)

## What is the expected behavior?
Page is not blank.

## What steps did you take to get this behavior?
Clicked on the button.

### Operating System
Windows 10
### Browser
Chrome

**Comment by kylemh** [comment]
In this specific area, I think we can eventually create a form to handle the idea of proposing new meetups.

In regards to `mailto:` links in general... I added `target="_blank"` at the behest of [Chris Coyier](https://css-tricks.com/all-about-mailto-links/). Unfortunately, desktops where mail is handled by a native app (or Windows 10 by default) will first open a new tab. I think removing `target="_blank"` from such links is a good move after reading more, so I can get on that.

**Comment by juliantrueflynn** [comment]
I'm doing this
