### ISSUE TITLE
Dynamically generate sitemap.xml

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#595]
# Feature request
`sitemap.xml` is important for SEO reasons. It's not tightly coupled to any new pages created, so we could forget to update the file if we add pages. By automatically generating it when new pages are added, we'd be dong ourselves a big favor!

## Proposed solution
1) Create a script which dynamically generates `sitemap.xml`. [Here's a tutorial for that](https://dev.to/embiem/auto-generate-sitemapxml-in-nextjs-2nh1).
2) As part of a pre-commit hook, check to see if new pages were added. If it's an authenticated route, do nothing (if it's decorated with `withAuthSync`). If there are new pages, run the script and add the newly changed file to staging before finishing the commit.

**Comment by sumitparakh** [comment]
Hey, I wanna do this.

**Comment by kylemh** [comment]
@sumitparakh jump in!
