### ISSUE TITLE
Alert for social sign-ons is too big

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#597]
# Bug Report
## What is the current behavior?
When getting an error from social sign-ons (Facebook or Google), the Alert component renders too clumped up and too large.

## What is the expected behavior?
The alert that shows up is 1rem away from both the inputs and the social sign on buttons. It's also no wider than both the buttons combined (or 100% of the available space, whichever comes first)

## What steps did you take to get this behavior?
Try to register using my Google sign-on using an email that was already registered.

### Operating System
MacOS Latest

### Browser
Chrome latest

### Is This A Third-Party Issue?
No

### Screenshots
![Screen Shot 2019-06-12 at 1 30 52 AM](https://user-images.githubusercontent.com/9523719/59335593-be38bc00-8cb1-11e9-95b6-39b87746f627.png)
![Screen Shot 2019-06-12 at 1 29 45 AM](https://user-images.githubusercontent.com/9523719/59335594-be38bc00-8cb1-11e9-821a-6d6492515e56.png)

**Comment by ecaoile** [comment]
I'll take care of this.
