### ISSUE TITLE
Attempting to login w/ SSO w/ an existing email does not work

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#599]
# Bug Report
## What is the current behavior?
I registered `kylemh.email@gmail.com` thru the website's form.
When logged out, I tried to login to this email via the Google and Facebook SSO, but received the error: ```"User is already registered with this e-mail address"```.

## What is the expected behavior?
Either:
1) IDEAL: We authenticate the user as the originally created account. This seems fair and safe since we're confirming emails upon registration.
2) DUCT-TAPE: We should adjust the error message to say: ```Please login using the form above.```

## What steps did you take to get this behavior?
Described above.

### Desired Solution
Use `/auth/social/<provider>/connect` endpoint and provide an interface where a user can connect SSO if they originally registered using the form.

See back-end documentation: https://api.operationcode.org/docs/

**Comment by kylemh** [comment]
@AllenAnthes 👀

**Comment by AllenAnthes** [comment]
> This seems fair and safe since we're confirming emails upon registration.

We're not.  We send the confirmation email but it isn't actually required.  In order to make it required we'd have to rework the registration flow, since they'd have to confirm before they could access the `UpdateProfileForm`.

**Comment by kylemh** [comment]
Can we do something corporeal that doesn't interrupt registration flow?

Example: User sees same flow, but is an "unverified" registrant. If they don't verify their email in X days, their account is deleted.

**Comment by AllenAnthes** [comment]
@kylemh Duct-tape implemented in backend.
![image](https://user-images.githubusercontent.com/27715246/59690290-ce1b3900-91a6-11e9-8fb3-75cb0636cd10.png)

**Comment by kylemh** [comment]
ty
