### ISSUE TITLE
Facebook SSO on Desktop fails with unhelpful error

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#601]
# Bug Report
## What is the current behavior?
If a Facebook login fails (may or may not be because the email is tied to a form-registered user), we get an Alert that just says ```"Incorrect value"```

## What is the expected behavior?
Error should explain simply to a user what went wrong (and an action item if they can fix the issue themselves).

## What steps did you take to get this behavior?
- Go to www.operationcode.org/login and click Facebook login
- Try to use `kylemh.email@gmail.com` Facebook account
- Get error in screenshots

### Operating System
MacOS Latest

### Browser
Chrome Latest

### Is This A Third-Party Issue?
Maybe?

### Screenshots
![Screen Shot 2019-06-12 at 1 48 20 AM](https://user-images.githubusercontent.com/9523719/59337104-c34b3a80-8cb4-11e9-8f1a-4075bf5dd035.png)
![Screen Shot 2019-06-12 at 1 48 18 AM](https://user-images.githubusercontent.com/9523719/59337106-c34b3a80-8cb4-11e9-94de-99ef212e7c09.png)
![Screen Shot 2019-06-12 at 1 48 16 AM](https://user-images.githubusercontent.com/9523719/59337107-c34b3a80-8cb4-11e9-841e-7c9e77220554.png)

**Comment by kylemh** [comment]
@AllenAnthes  👀

**Comment by AllenAnthes** [comment]
Looks like we've got a configuration mismatch somewhere.  The request from the BE to Facebook to verify the provided token is valid is failing.  When I use the development Facebook creds I get the correct error.
![image](https://user-images.githubusercontent.com/27715246/59353116-e04d3100-8ce7-11e9-9ca9-1a25b9be7247.png)

**Comment by kylemh** [comment]
Resolved.
