### ISSUE TITLE
Mobile browsing bug - logo disappears

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/front-end#602]
# Bug Report
## What is the current behavior?
The logo disappears when traversing the site
Pixel 2 - chrome.

## What is the expected behavior?
The logo does not disappear when traversing the site

## What steps did you take to get this behavior?
Reported on LinkedIn from Joseph Richardson

**Comment by kylemh** [comment]
If anybody reading this has a Pixel 2 w/ Chrome please attempt to replicate and report back!

**Comment by SpaceGuru01** [comment]
Seems to be working using the Chrome Dev Tools Device. I'll see if I can get my emulator to work.

**Comment by kylemh** [comment]
Gonna go ahead and close this ticket. If somebody sees this issue, please include reproduction steps!
