### ISSUE TITLE
Forks Don't Record Cypress Videos

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#608]
# Bug Report
## What is the current behavior?
https://github.com/OperationCode/front-end/pull/606
https://circleci.com/gh/OperationCode/front-end/528?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

## What is the expected behavior?
All Cypress videos are recorded in CI

## What steps did you take to get this behavior?
Looked at logs

### Is This A Third-Party Issue?
Maybe?

### Screenshots
![Screen Shot 2019-06-15 at 8 39 04 PM](https://user-images.githubusercontent.com/9523719/59558740-ebd17e00-8fad-11e9-87a8-48c5c1413cb1.png)

**Comment by AllenAnthes** [comment]
Fixed in circleCI configs
