### ISSUE TITLE
Create GitHub SSO button and integrate with endpoint

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#614]
# Feature request
We have the ability for users to register and login using Facebook and Google live. Now, we also have the ability to login and register using GitHub.

See 06/03/19 - deployed to test

See `/auth/social/github/` in [our API docs](https://api.operationcode.org/docs/)

## Proposed solution
- Create a GitHub SSO button (that is very similar in appearance to the existing SSO buttons) and render it in `SocialLoginButtons` component.
- Convert the `SocialLoginGroup` component to display all of the buttons in a single-file, vertical column on all viewports.
- Make any necessary changes to `SocialLoginGroup` for GitHub-specific SSO handling.

**Comment by Shobhit1** [comment]
If no one takes this, I can give it a try. Please let me know what is the expected time span for this feature/issue?

**Comment by kylemh** [comment]
No timespan, @Shobhit1 - feel free to grab it at your earliest convenience.

**Comment by tfquirk** [comment]
I would be happy to work on these three deliverables

**Comment by kylemh** [comment]
You'll wanna message @AllenAnthes and work on the [back-end](https://github.com/OperationCode/back-end) first

**Comment by sumitparakh** [comment]
Hey, is back-end ready? If yes, i wanna implement the front end part.

**Comment by kylemh** [comment]
@AllenAnthes
