### ISSUE TITLE
"Warning: React does not recognize the `trackerNames` prop on a DOM element."

### ISSUE THREAD

**Issue by juliantrueflynn** [OperationCode/front-end#625]
# Bug Report
## What is the current behavior?
Browser console error in title

## What steps did you take to get this behavior?
Opened /contact page and looked at browser console

### Operating System
Ubuntu 16.04

### Browser
Chromium

**Comment by kylemh** [comment]
saw this as well. This comes for the ReactGA lib. I didn’t spend time to see if I could prevent it.

**Comment by juliantrueflynn** [comment]
@kylemh for sake of record: we talked on Slack and latest react-ga update caused this. Reverting to 2.5.7 seemed to remove console error and submitting PR.

I'm going to see if react-ga is open to a PR to fix this too.
