### ISSUE TITLE
Add ability to filter by VET-TEC on code schools page

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/front-end#638]
# Feature request
More coding bootcamps are being approved to accept VET-TEC as part of the new Forever GI Bill, and we should find a way to highlight them.

## Proposed solution
A way to view on our Code Schools page, which schools accept VET-TEC money.

## Additional context
List of approved schools is at https://benefits.va.gov/GIBILL/FGIB/VetTecTrainingProviders.asp

**Comment by kylemh** [comment]
I don't think we'll need a design or mock. Should be simple enough to add another filtering mechanism.

The code schools page needs some polish anyways. I'll tackle this tonight.

**Comment by kylemh** [comment]
Blocked by needing new field on back-end for code_schools endpoint... Making ticket on back-end.

I can do some, but not all the work needed for this!

**Comment by kylemh** [comment]
Linked issue to blocking back-end ticket.

**Comment by kylemh** [comment]
Unblocked. Field now exists as `isVetTecApproved`

**Comment by hollomancer** [comment]
Do we need any design for an icon or something like that?

**Comment by kylemh** [comment]
Gimme a shot, and lemme know what ya think?
