### ISSUE TITLE
Remove `Reserving Issues` Guidance

### ISSUE THREAD

**Issue by jack-robs** [OperationCode/front-end#662]
# Feature request
Update FE docs to remove reserving issues

## Proposed solution
Edit this page, make pr: https://github.com/OperationCode/front-end/blob/master/CONTRIBUTING.md

## Potential alternative solutions
n/a

## Additional context
As a FOSS project with limited ability for oversight, we'd like to de-friction the user interest -> user PR process.

**Comment by kylemh** [comment]
On it
