### ISSUE TITLE
Getting Data from Sessions for Analytics 

### ISSUE THREAD

**Issue by jack-robs** [OperationCode/front-end#663]
# Feature request
-Get data from sessions and use it for user-base analytics, and then build telemetry into Slack channel to support week-over-week goals. 

## Proposed solution
Unk so far - Research

**Comment by kylemh** [comment]
Assigning this one back to you!

**Comment by jack-robs** [comment]
haha I wish I had the tech chops to implement... I can track down some resources though

**Comment by kylemh** [comment]
Sorry. I was confused by this ticket. We do track a lot of data from sessions. What would you like to see specifically in Slack?
