### ISSUE TITLE
Accessibility: Navigation submenus should only have 1 open at any time

### ISSUE THREAD

**Issue by jack-robs** [OperationCode/front-end#664]
# Feature request
for keyboard accessibiity is when another submenu opens, if another is already open, close the previously opened one so that if someone using a screenreader tabs backwards, they're aware of the current context.

## Proposed solution
Unk - research/propose one w/ PR as well

## Potential alternative solutions
n/a

## Additional context
A11Y audit

**Comment by danielasannino** [comment]
Will tackle this one.
