### ISSUE TITLE
Update download behavior in /podcast

### ISSUE THREAD

**Issue by cbituin** [OperationCode/front-end#674]
# Bug Report
## What is the current behavior?
All media/.mp3 files download simultaneously.
 
## What is the expected behavior?
After navigating to the page, the media file should only download after the user clicks the "play" button.

## What steps did you take to get this behavior?
Navigate to https://operationcode.org/podcast

**Comment by kylemh** [comment]
At a high level, we simply don't want podcasts to download until _after_ somebody clicks the play button. This can be accomplished a number of ways, but the **best** way would be to communicate with the `react-player` GitHub repo on how to achieve the functionality.

The **easiest** way might be to ditch the player and create our own. Note: I don't mean to imply it's easy, but that it's easier than working on a repo we don't control.
