### ISSUE TITLE
Navigating to /podcast page broken for Safari and Edge

### ISSUE THREAD

**Issue by cbituin** [OperationCode/front-end#681]
# Bug Report
## What is the current behavior?
Users reporting 404 error when refreshing page or navigating to page from footer.

## What is the expected behavior?
The /podcast page should load regardless 

## What steps did you take to get this behavior?
Navigate to operationcode.org, click "Podcast" link under "Deploy the Future" or within footer.

### Browser
- Safari
- Edge
- potential for others

### Screenshots

Console log on page on Safari
<img width="1267" alt="Screen Shot 2019-07-15 at 1 56 20 PM" src="https://user-images.githubusercontent.com/28311826/61238851-8509c680-a70b-11e9-95dd-efc8b3f1cfaa.png">

**Comment by rsupak** [comment]
<img width="1267" alt="Screen Shot 2019-07-15 at 1 56 20 PM" src="https://user-images.githubusercontent.com/28311826/61238851-8509c680-a70b-11e9-95dd-efc8b3f1cfaa.png">

**Comment by kylemh** [comment]
Appended to OP @rsupak
