### ISSUE TITLE
Add LogRocket as a sponsor

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#712]
# Feature request
We advertise every organization that supports us. LogRocket is giving us 2,500 recorded sessions a month instead of the usual 1,000 for OSS plans. ❤️ We have to add them to the sponsors section!

## Proposed solution
Add them!

**Comment by IAMOTZ** [comment]
Hi @kylemh 
I would like to work on this.

**Comment by IAMOTZ** [comment]
It seems the logo for this sponsor has to be hosted in an s3 bucket, please can you help with the link(or path) to the logo? Thanks.

**Comment by kylemh** [comment]
Added!

```https://operation-code-assets.s3.us-east-2.amazonaws.com/partnerLogos/logrocket.png```

**Comment by IAMOTZ** [comment]
Hi there!
I noticed all the other sponsor logos are of the dimension 100x100, however, the LogRocket logo you posted above has a dimension of about 459x100, this really affects the layout of the logos. Do you want me to add it like that or you are going to resize the image?

**Comment by kylemh** [comment]
I'll fix the image for you. Apologies.

**Comment by kylemh** [comment]
Done 💥

**Comment by IAMOTZ** [comment]
Cool. I've got the PR here: https://github.com/OperationCode/front-end/pull/715
