### ISSUE TITLE
Add Leadership Circle recognition to website

### ISSUE THREAD

**Issue by Lianis-OperationCode** [OperationCode/front-end#713]
# Bug Report
## What is the current behavior?
No recognition on [the leadership circle page](www.operationcode.org/leadership_circle), when there should be.

## What is the expected behavior?
Recognition of all donors in the following shape, underneath the first section on www.operationcode.org/leadership_circle

### Simple mock
![Screen Shot 2019-08-08 at 2 21 26 PM](https://user-images.githubusercontent.com/9523719/62738708-d2661480-b9e7-11e9-88f4-3740e1fa5c39.png)

### The donor data
[2018 Leadership Circle list.pdf](https://github.com/OperationCode/front-end/files/3441419/2018.Leadership.Circle.list.pdf)

### Other Info
Non-developer members of Operation Code will need to update this data. Please ensure that the donors are placed into a sensible data structure as a separate file, and create a README tutorial next to that file to explain _every single step_ needed for somebody to update the file. Assume the readers know nothing about GitHub, but are able to navigate the browser and will bookmark your README file.

**Comment by kylemh** [comment]
@Lianis-OperationCode

Obviously this list is pretty dynamic... Unless we're storing this information somehow, the best way may be to create a public google doc (read-only) and that way David (or whoever) can update the list and rest assured people seeing the list from the website will be kept in sync.

Thoughts?

**Comment by Lianis-OperationCode** [comment]
Hi Kyle,

I created the list like you suggested. Let me know if something like
this works.

https://docs.google.com/spreadsheets/d/14KWiUCOyKnxBh9q992WbFLDCrpyAcH2zeeQevUhrKus/edit?usp=sharing

Thanks,

Lianis

**Comment by cbituin** [comment]
@kylemh @Lianis-OperationCode I've taken the list a step further - if we use a Google Form for intake (very user friendly and can be updated from any device), the updates automatically feed into a Google Sheet (similar to the previous Sheet created above). If you're good with that, perhaps we can use Google's Sheets API to dynamically update /leadership_circle.

Example of Google Form used:
![image](https://user-images.githubusercontent.com/38743840/62885409-ac918600-bced-11e9-816f-bc69fca8c466.png)

What automatically generates:
![image](https://user-images.githubusercontent.com/38743840/62885438-c763fa80-bced-11e9-9bdb-136035416429.png)

**Comment by kylemh** [comment]
I appreciate the effort, but we've actually elected to simply hard-code the benefactors until the dynamacy of their number becomes a problem. We've had the program going for over a year, and have fewer than 15 people.
