### ISSUE TITLE
Update list of Corporate Sponsors on website

### ISSUE THREAD

**Issue by Lianis-OperationCode** [OperationCode/front-end#714]
# Bug Report
## What is the current behavior?
Cash and in kind sponsors are listed together, when this isn't fair to folks who paid.

## What is the expected behavior?
Distinguish between paying and in kind sponsors by making paid logos larger and group together, while listing others in a separate manner with smaller logos. Paid sponsors are US Bank, Threatstack and Slack.

**Comment by kylemh** [comment]
Would love to get a mock of this from design @jack-robs

**Comment by chrisgalvan** [comment]
is the idea of group them similar to this https://2019.jsconf.us/sponsors/?
I could work on something real quick, or if you have an idea/mock let me know.

**Comment by kylemh** [comment]
Yes, maybe even with titles designating and explaining the differences in group.

**Comment by chrisgalvan** [comment]
what should the titles say? Paid Sponsors vs ''?

**Comment by kylemh** [comment]
In-Kind Sponsors

**Comment by kylemh** [comment]
So something like

## Paid Sponsors

These sponsors have donated cash to help keep the mission going here at Operation Code. They may or may not have also donated to our cause via others means.

---

## In-Kind Sponsors

The following organizations have helped Operation Code through services, products, advertisements, scholarships, or sponsorships. We thank them for their contributions.

**Comment by jasonappah** [comment]
I'll give this one a shot!

**Comment by Nikhil-Vats** [comment]
@jasonappah Are you working on this? If not, I would like to contribute to this. @kylemh Can I start working?

**Comment by jasonappah** [comment]
> I'll give this one a shot!

I ended up getting stumped as to how to filter the in-kind vs paid sponsors on the page.

**Comment by kylemh** [comment]
https://github.com/OperationCode/front-end/pull/889

Check out the way @chrisgalvan if you'd like to learn about one solution!

**Comment by jasonappah** [comment]
Thanks! I'll take a look!
