### ISSUE TITLE
Mobile navigation is not scrollable

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#726]
# Bug Report
## What is the current behavior?
When on mobile, a hamburger menu is shown on the page header which - when clicked - reveals the **mobile navigation** (`NavMobile`). That view is not able to scroll; not all items are visible.

## What is the expected behavior?
When a mobile user attempts to scroll within the `NavMobile` it should scroll the list of navigation links - not the rest of the app. If impossible, it's still more desirable to scroll both.

## What steps did you take to get this behavior?
Noticed a difference in the number of mobile nav links rendered on an iPhone 6 vs. iPhone X

**Comment by Austinmoore1492** [comment]
I don't have a way to test it out right now but just messing with the inspect element on Chrome and FireFox if I removed the positon: fixed; from the NavMobile class and removing the 100vh height on the dropdown class it allows to scroll but it does make everything scroll-able. So you can scroll down with the menu still open. May not be the ideal fix but I can look more when I have access to VS Code.

**Comment by kylemh** [comment]
For the styles applied to the `ul` in the `NavMobile` component, you simply need to add: `height: 100%;` and `overflow-y: auto;`

**Comment by jmayergit** [comment]
I've used the [body-scroll-lock](https://www.google.com/search?q=body+scroll+lock&rlz=1C5CHFA_enUS782US782&oq=body+scroll+lock&aqs=chrome..69i57j0l2j69i60l3.3913j1j7&sourceid=chrome&ie=UTF-8) package to prevent scrolling

**Comment by Austinmoore1492** [comment]
Easy enough. 
I think the ul already has overflow-y set to auto, so you should only have to add the height: 100%;

**Comment by Austinmoore1492** [comment]
I need something like body-scroll-lock for project, thank you for mentioning it @jmayergit

**Comment by isa3bel** [comment]
Is this issue resolved?

**Comment by kylemh** [comment]
@isa3bel nope!

**Comment by isa3bel** [comment]
after opening the mobile version, there didn't seem to be a need to scroll, all items seem to be visible ending with Donate.

**Comment by kylemh** [comment]
@isa3bel look again - it just coincidentally looks clean, but items are missing.
