### ISSUE TITLE
LinkedIn meta images are inconsistent and incorrect

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#727]
# Bug Report
## What is the current behavior?
Sharing links on LinkedIn reveals inconsistent images, and they're all either incorrect or revealed as a bad ratio.

## What is the expected behavior?
It looks perty

## What steps did you take to get this behavior?
Shared `https://www.operationcode.org/` on LinkedIn

## Additional Info
- [Info on reqs from LinkedIn](https://www.linkedin.com/help/linkedin/answer/46687/making-your-website-shareable-on-linkedin?lang=en)
- [A way to test you changes](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Foperationcode.org%2Fjoin). Simply make a PR and pass the preview deployment URL.

### Screenshots
![Screen Shot 2019-08-08 at 2 48 03 PM](https://user-images.githubusercontent.com/9523719/62740077-8b7a1e00-b9eb-11e9-8ce8-0028ddeb6af2.png)
![Screen Shot 2019-08-05 at 3 02 36 PM](https://user-images.githubusercontent.com/9523719/62740083-903ed200-b9eb-11e9-90f6-5e88af4248cd.png)

**Comment by kevinkiklee** [comment]
Posting this for reference to whoever is tackling this:  https://ogp.me/

This isn't just for LinkedIn, but for every time the website is shared.  It needs to follow the OG protocol for OpCode site to not look like ass everywhere.

**Comment by isa3bel** [comment]
I may try to tackle this!

**Comment by prmsrswt** [comment]
I would like to take up this issue. I have looked into the resources @kevinkiklee and @kylemh provided. From what I have understood, we need at least `og:title`, `og:type`, `og:url`, `og:image`, `og:image:alt` and `og:description` meta tags, and the image should be `1.91:1` for best results. Is there anything else I am missing?

**Comment by kylemh** [comment]
If you check out `components/head.js` you'll see that we have:

```jsx
import NextHead from 'next/head';
import { element, string } from 'prop-types';
import { s3 } from 'common/constants/urls';

Head.propTypes = {
  children: element,
  title: string,
  description: string,
  url: string,
  ogImage: string,
};

Head.defaultProps = {
  children: undefined,
  title: undefined,
  description:
    // eslint-disable-next-line max-len
    'Operation Code is a 501(c)(3) non-profit dedicated to helping military members, veterans, and their families to learn how to get a job in the tech industry.',
  url: 'https://operationcode.org',
  ogImage: `${s3}branding/logos/small-blue-logo.png`,
};

function Head({ children, title, description, url, ogImage }) {
  return (
    <NextHead>
      <meta charSet="UTF-8" />
      <title>Operation Code{` | ${title}`}</title>
      <meta name="description" content={description} />

      <meta property="og:url" content={url} />
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />

      <meta name="twitter:site" content={url} />
      <meta name="twitter:image" content={ogImage} />
      <meta property="og:image" content={ogImage} />

      {/* Constant meta tags are supplied in `_document.js` */}

      {/* children must be `<link>` or `<meta>` */}
      {children}
    </NextHead>
  );
}

export default Head;
```

Looks like we could use `og:type` and `og:image:alt`. Thanks for the specific image ratio! I uploaded a correct one: https://operation-code-assets.s3.us-east-2.amazonaws.com/branding/og_meta_image.png

You can change the default prop for `ogImage` with the above.

https://operation-code-assets.s3.us-east-2.amazonaws.com/branding/logos/small-blue-logo.png
