### ISSUE TITLE
Make the `Heading` component act as scroll anchor

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#729]
# Feature request
As a user, I'd love to be able to scroll to specific sections of our pages and link people to that exact section.

**Example:**
https://scrollmagic.io/examples/advanced/anchor_link_scrolling.html#middle

## Proposed solution
Make edits to the `Heading` component to render a link icon (use [this icon from FontAwesome](https://fontawesome.com/icons/link?style=solid)), but conditionally make it visible only on hover. Clicking it should change the route to include the hash of the scroll anchor and move the viewport such that the clicked header is at the top of the view.

**Comment by walleyyang** [comment]
I'll work on this.
