### ISSUE TITLE
Migration to typescript

### ISSUE THREAD

**Issue by sumitparakh** [OperationCode/front-end#766]
# Feature request

I see that we are using prop-types for basic type checking. But instead of prop-types, why don't we use typescript and experience better type safety environment? Is there any 
future plan for migrating to typescript? 

## Proposed solution

If there is any migration plan, I would love to contribute.

**Comment by kylemh** [comment]
I have no plans for that, but am interested in hearing from existing contributors on whether or not it's something they desire.

While PropTypes are often considered fragile, we have a Jest plugin that throws an error if there’s ever a PropType error/warning so it’s a bit of a stricter system. I - personally - have not seen issues in this project which TS would resolve.

**Comment by kylemh** [comment]
I'll go ahead and close this.

I'll be making our component library using TypeScript FWIW!
