### ISSUE TITLE
Add Copy: Join page

### ISSUE THREAD

**Issue by ksmacleod99** [OperationCode/front-end#768]
# Feature request
Add the same copy from the _Who Do We Serve_ page to the _Join_ page (https://operationcode.org/join), just in case someone bypasses the information. Everything but the quotation marks, please. 
Related issue: #767 

## Proposed solution
"We work closely with military veterans, service members, and spouses who are passionate about transitioning into the tech industry. We work with over 5,000 members who are all working towards relevant goals on Slack and in-person MeetUps. Membership is free!"

**Comment by kylemh** [comment]
`meet-ups` instead of MeetUps
