### ISSUE TITLE
Ban future imports of enzyme using ESLin

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#840]
# Feature request
I want this code base to only use `@testing-library/react` going forward.

## Proposed Solution

Use [no-restricted-imports](https://eslint.org/docs/rules/no-restricted-imports) to ban ESLint for future usages. Add `// eslint-ignore-next-line no-restricted-imports` on all existing instances. Add a message indicating to devs they should use `@testing-library/react`

**Comment by RanadeepPolavarapu** [comment]
I'll take this.
