### ISSUE TITLE
Migrate to Hooks

### ISSUE THREAD

**Issue by ojaswa1942** [OperationCode/front-end#845]
The code presently uses class components & lifecycle methods.
However, React 16.8.0 release introduces a more intuitive & functional approach towards development which is more likely to be used in the future.

## Steps to resolve the issue:
Replace Class and Class-based methods (state, lifecycle, PureComponent etc.) to functional approach (useState, useEffect, memo, etc.)

## Keep in mind:
https://github.com/OperationCode/front-end/issues/867

## Note

Comment the names of the 5 components you plan on migrating before tackling them so you don't step on anybodys' toes.

**Comment by ojaswa1942** [comment]
We can do the migration in parts - per component basis.. rather than completely migrating all the components together. Anyway, I'd like to carry this forward.

**Comment by manthonyg** [comment]
Here is a link to the docs

https://reactjs.org/docs/hooks-overview.html

> Crucially, Hooks work side-by-side with existing code so you can adopt them gradually. There is no rush to migrate to Hooks. We recommend avoiding any “big rewrites”, especially for existing, complex class components. It takes a bit of a mindshift to start “thinking in Hooks”. In our experience, it’s best to practice using Hooks in new and non-critical components first, and ensure that everybody on your team feels comfortable with them. >

**Comment by kylemh** [comment]
I would personally love to see #850 done before this, but I see nothing wrong with somebody doing this work!

Similar to what I said in #850, I’ll consider somebody having contributed towards this PR if they convert 5 components.

**Comment by ojaswa1942** [comment]
@kylemh great, I'll go ahead then

**Comment by rusye** [comment]
@ojaswa1942 are there any components that you are concentrating on?
@kylemh I'm not that good with tests but do you know of anyone else switching to hooks?

**Comment by kylemh** [comment]
Well, if you’re not comfortable writing tests, I think trying a to handle a few from #850 is a great idea.

You already know the assertions and the tests already pass. You’ve just got to change the way that each test runs! Give it a shot.

**Comment by ojaswa1942** [comment]
Going my way from simpler components such as buttons, and cards to more complicated components such as nav and forms.

**Comment by gagandeepp** [comment]
That sounds good I will be working on it as well

**Comment by chynh** [comment]
Hey all, I am also interested in contributing to this issue. Currently working on a few simple components.

**Comment by kylemh** [comment]
@gagandeepp @chynh @ojaswa1942 would you please just type out the names of the components you'll tackle here so we don't get overlap?

**Comment by chynh** [comment]
@kylemh I can work on ZipRecruiterJobs, join, SocialGroupLogin, change_password, ChangePasswordForm.

**Comment by ojaswa1942** [comment]
I can work on FlatCard, SchoolCard, Nav, NavMobile, NavListItem.

**Comment by joshwooding** [comment]
I can work on Button, CloseButton, Professional Details, Technology and Military Details.

**Comment by kylemh** [comment]
@joshwooding, I would avoid the Multi-step form component and any Multi-Step Form's steps (you listed Professional Details, Technology, and Military Details).

I'll edit OP to indicate which ones are super duper hard.

**Comment by joshwooding** [comment]
@kylemh Cool, I've updated the list above. Is it okay now?

**Comment by kylemh** [comment]
💯

**Comment by ojaswa1942** [comment]
Hey, I'm not well-versed with testing yet and the tests for the Nav components fail after porting to hooks.
`ShallowWrapper::state() can only be called on class components`
It seems that the functions in tests used are only for class components. I tried finding an alternative but couldn't find a decent non-"react-testing-library" solution.
Please help out :(

**Comment by ojaswa1942** [comment]
`When using state from hooks, your test must ignore implementation details like state in order to properly test it. You can still make sure the component passes the correct state into its children.` they say..
@kylemh  In that case, I can rewrite to not test the state variation, but the reaction of that state change?

**Comment by kylemh** [comment]
Yep! That’s why I mentioned that #850 would be a good move to do first, but there exist SOME components that don’t test implementation details so it wasn’t a hard rule.

I’m almost home from work and I’ll rework that test for you 👍

**Comment by kylemh** [comment]
@ojaswa1942 done 💃 with Nav and NavMobile https://github.com/OperationCode/front-end/pull/861

**Comment by kylemh** [comment]
Keep https://github.com/OperationCode/front-end/issues/867 in mind y'all!

**Comment by itaditya** [comment]
@kylemh can I work on a separate PR to migrate UpdateProfileForm to hooks as well as writing its tests with @testing-library/react? Would it be counted separately?

> ## Components to ignore because they're going to be difficult:
> 
>     * Anything under `components/UpdateProfileForm` folder

**Comment by frontend210** [comment]
Hi @kylemh  I am new guy to Operation projects, who want to contribute.

**Comment by kylemh** [comment]
@itaditya sounds good to me!

**Comment by kylemh** [comment]
Here are all that are left!

[Looks like Next.js actually enables functions as well as classes](https://github.com/zeit/next.js#fetching-data-and-component-lifecycle), so those are back on the menu.

![Screen Shot 2019-10-14 at 12 21 22 AM](https://user-images.githubusercontent.com/9523719/66734603-96e92b80-ee18-11e9-92e5-a9349cbe81d6.png)

**Comment by LeviButcher** [comment]
I'll migrate over **LoginForm, RegistrationForm, PasswordResetForm, code_schools, and _error**

**Comment by JakobTeske** [comment]
I'll migrate  **Team**, **UpdateProfile**, **Podcast**, **PasswordReset** and **PasswordResetConfirm**

**Comment by kylemh** [comment]
Whoops

**Comment by ojaswa1942** [comment]
Any updated list of available components?

**Comment by kylemh** [comment]
`UpdateProfileForm`, `withAuthSync`, `nextContextMock`, and `createPage/builders` is all that remains

**Comment by 3b3ziz** [comment]
I will migrate UpdateProfileForm.

**Comment by rusye** [comment]
I'll do `withAuthSync`

**Comment by rusye** [comment]
Could anyone give me advice with `nextContextMock`?  

I'm not exactly certain what I need to return to make it all work, here is what I have so far: `/* eslint-disable react/sort-comp */
import React from 'react';
import { any, object } from 'prop-types';
import MockedRouter from './nextRouterMock';

// https://github.com/zeit/next.js/issues/5205#issuecomment-422846339

MockNextContext.propTypes = {
  // eslint-disable-next-line react/forbid-prop-types
  children: any.isRequired,
  headManager: object,
  router: object,
};

MockNextContext.defaultProps = {
  headManager: {},
  router: {},
};

MockNextContext.childContextTypes = {
  headManager: object,
  router: object,
};

export default function MockNextContext({ headManager, router, children }) {

  getChildContext() {
    // const { headManager, router } = this.props;
    return {
      headManager: {
        updateHead() {},
        ...headManager,
      },
      router: {
        asPath: '/',
        route: '/',
        pathname: '/',
        query: {},
        back() {},
        beforePopState() {},
        prefetch() {},
        push() {},
        reload() {},
        replace() {},
        events: {
          on() {},
          off() {},
          trigger() {},
        },
        ...MockedRouter,
        ...router,
      },
    };
  }

  return (
    // const { children } = this.props;
    children;
  )
}
`

**Comment by rusye** [comment]
@kylemh I don't have the time to deep dive into custom hooks at the moment so if you could delete my PR #930 so that it could be opened up to someone else it would be greatly appreciated.

**Comment by kylemh** [comment]
No need! I'll close it if/when it gets resolved by anybody.

**Comment by kylemh** [comment]
Good work everybody! We ended up not touching `nextContextMock` and `withAuthSync` as they depend on Next.js specific things.

I'm gonna be working on distributing the Operation Code t-shirts ASAP from Hacktoberfest
