### ISSUE TITLE
Migrate off of enzyme to react testing-library

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#850]
# Feature request

Using react testing-library means our tests will be more centered around the DOM and I’ll have more confidence in their value. Also, our tests will be less likely to change.

## Proposed solution

- Uninstall all enzyme dependencies
- Redo all tests using enzyme with react testing-library.
- Remove the lint rule banning enzyme imports.

Note: this is a lot of work for a single PR. Feel free to do this in small chunks! In regards to our Hacktoberfest prizes, I’ll consider you as having a claim to consider this a resolve issue if you change at least 5 suites.

## Note
When doing the conversion please follow the following pattern:
```jsx
const component = render(<JSX />);
// or
const { container } = render(<JSX />);
```

`wrapper` is a term usually referring to enzyme wrappers.

## Example Conversion PR
https://github.com/OperationCode/front-end/pull/861

Comment the names of the 5 suites you plan on migrating before tackling them so you don't step on anybodys' toes.

## Progress:
|Test file   |Assigned|
|---|---|
|  ErrorDisplay |  @vobango |
|  Label | @vobango  |
|  Modal | @vobango  |
|  OutboundLink |  @vobango |
|  YouTubeVideo |  @vobango |
|  SocialLoginGroup | @chynh  |
|  MilitaryDetails | @chynh  |
|  MilitaryStatus |  @chynh |
|  ProfessionalDetails |  @chynh |
|  Technology | @chynh  |
|  Badge | @itaditya |
|  Button | @itaditya  |
|  FlatCard |  @itaditya |
|  SchoolCard | @itaditya  |
|  LinkButton | @itaditya |
|  CloseButton | @LeviButcher |
|  Select | @LeviButcher |
|  NavListItem | @LeviButcher |
|  ArticleGroup | @LeviButcher |
|  RegistrationForm | @LeviButcher |
|  Input | @calincionca35  |
|  YoutubeVideo | @calincionca35 |
|  LoginForm | @calincionca35 |
|  ChangePasswordForm | @calincionca35 |
|  PasswordResetForm | @calincionca35 |

**Comment by itaditya** [comment]
I'd love to work on it. Can you tell me which 5 tests are the most impactful and you would benefit the most by migrating to react-testing-library.

**Comment by kylemh** [comment]
I appreciate the gesture, but you can just pick 5 at random! The longest ones will be the least likely to get done by the community! If you feel so inclined, just tackle the biggest test files first.

**Comment by vobango** [comment]
I would like to contribute to this aswell.
@itaditya have you chosen which tests to work on so we don't accidentally migrate the same ones.

**Comment by itaditya** [comment]
Good point @vobango. I'll let you know by today. If you have started working on some test let me know as well, I won't pick those.

**Comment by vobango** [comment]
Thanks! I will probably start working on this tomorrow so I'll give an update then.

**Comment by kylemh** [comment]
Comment the names of the 5 suites you plan on migrating before tackling them so you don't step on anybodys' toes!

**Comment by rusye** [comment]
@kylemh Would the guys that are working on hooks be rewriting the tests at the same time?  So just curious if I should proceed with this.

https://github.com/OperationCode/front-end/issues/845#issuecomment-540273543

**Comment by kylemh** [comment]
They aren't necessarily, but it'd be cool if they decided to! Great way to knock out 2 PRs at once.

**Comment by rusye** [comment]
A lot of overlapping happening, I guess I'll have to monitor what goes on in both of the issues.

**Comment by kylemh** [comment]
You can easily do any of these on their own.

You may or may not be able to do some from #845 without changing the tests.

**Comment by rusye** [comment]
@kylemh thank you for the example :)

**Comment by vobango** [comment]
I chose **ErrorDisplay**, **Label**, **Modal**, **OutboundLink** and **YouTubeVideo** suites as they weren't mentioned in #845 
If anyone has already started working on any of those, please let me know, I'll choose another suite.

**Comment by chynh** [comment]
I would like to work on **SocialLoginGroup.test.js**, **MilitaryDetails.test.js**, **MilitaryStatus.test.js**, **ProfessionalDetails.test.js**, **Technology.test.js**.

**Comment by itaditya** [comment]
I will work on **Badge.test.js, Button.test.js, FlatCard.test.js, SchoolCard.test.js, LinkButton.test.js**

**Comment by itaditya** [comment]
Here's a better representation

|Test file   |Assigned|
|---|---|
|  ErrorDisplay |  @vobango |
|  Label | @vobango  |
|  Modal | @vobango  |
|  OutboundLink |  @vobango |
|  YouTubeVideo |  @vobango |
|  SocialLoginGroup | @chynh  |
|  MilitaryDetails | @chynh  |
|  MilitaryStatus |  @chynh |
|  ProfessionalDetails |  @chynh |
|  Technology | @chynh  |
|  Badge | @itaditya |
|  Button | @itaditya  |
|  FlatCard |  @itaditya |
|  SchoolCard | @itaditya  |
|  LinkButton | @itaditya |

**Comment by kylemh** [comment]
I'll put that into OP on next update and maintain it

**Comment by kylemh** [comment]
Another note I added to OP, cuz it's hard to make a lint rule for it and I'm seeing many people do it.

When doing the conversion please follow the following pattern:
```jsx
const component = render(<JSX />);
// or
const { container } = render(<JSX />);
```

`wrapper` is a term usually referring to enzyme wrappers.

**Comment by LeviButcher** [comment]
I will convert **CloseButton, Select, NavListItem, ArticleGroup, and RegistrationForm**.

From what I can tell **UpdateProfileForm, PasswordResetForm, and LoginForm** are left.

**Comment by kylemh** [comment]
@LeviButcher assigned 👍

**Comment by kylemh** [comment]
I see Badge, Button, FlatCard, SchoolCard, ChangePasswordForm, MultiStepForm, Input, Label, Select, LinkButton, NavListItem, PasswordResetForm, RegistrationForm, UpdateProfileForm, YouTubeVideo all still using enzyme.

**Comment by LeviButcher** [comment]
Ah my bad. I didn't realize CloseButton and ArticleGroup had been done. I will replace those with PasswordResetForm and UpdateProfileForm.
I got 3 out of 5 and should be ready soon. :+1:

**Comment by frontend210** [comment]
Hi @kylemh I'd like to run into converting on Badge, Button, FlatCard, SchoolCard.
Can you please assigned them to me?

**Comment by kylemh** [comment]
@frontend210 all of those have been done already! You'll want to simply do a global search for `from 'enzyme';` in the code base to find spots that need a refactor!

**Comment by prmsrswt** [comment]
I would like to do some of these, I think no one is converting `ChangePasswordForm`, `Input`, `MultiStepForm`, `LinkButton` so I would like to take them on. Also @LeviButcher converted `LoginForm` in place of `UpdateProfileForm` in #879 so I guess `UpdateProfileForm` is still up for grabs.

**Comment by kylemh** [comment]
@prmsrswt check out the OP table - some of those are taken

**Comment by prmsrswt** [comment]
Oh, my bad. I actually converted `ChangePasswordForm` and `Input` tests :sweat_smile: so if anyone wants a reference they can take a look [at the diff here](https://github.com/OperationCode/front-end/compare/master...prmsrswt:react-testing-patch).

Should I convert `MultiStepForm` an `UpdateProfileForm` then?

**Comment by kylemh** [comment]
Those will be girthy - I'll count it as 5 for you 💃
