### ISSUE TITLE
Upgrading Cypress leads to a very flakey test

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#851]
# Bug Report
## What is the current behavior?
Our Cypress tests are a little flakey, but not prohibitively so. On #718, [tests simply timeout](https://circleci.com/gh/OperationCode/front-end/3174?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), and we're not sure why.

@AllenAnthes any context you can provide in the comments, please do!

## What is the expected behavior?
CI can pass regularly.

**Comment by bautistaaa** [comment]
I work with cypress pretty extensively.. I can take look

**Comment by kylemh** [comment]
https://dashboard.cypress.io/#/projects/dbquo6/runs/2001/specs here is a failing spec. I've seen the failure above pretty rarely, and I've seen the other code school page error (the one about IntersectionObserver in the link). Both are the flakey ones that I'm okay with. 

This Cypress upgrade leads to like 90% failures which sucks...

**Comment by kylemh** [comment]
Also, looks like [other people have been experiencing the same issue](https://github.com/cypress-io/cypress/issues/5139).

Luckily, [it appears that a possible solution will be released shortly](https://github.com/cypress-io/cypress/issues/5139#issuecomment-537232858)!

**Comment by kylemh** [comment]
Closed in #960
