### ISSUE TITLE
Make the form flow in a single direction.

### ISSUE THREAD

**Issue by itaditya** [OperationCode/front-end#854]
# Bug Report
## What is the current behavior?
Currently the SignUp form is designed like this

<img width="748" alt="image" src="https://user-images.githubusercontent.com/15871340/66318405-dd321c80-e938-11e9-9fc9-0d5b6b364f24.png">

## What is the expected behavior?
The form should flow in one direction from top to bottom.

## Why is it bad?

It is a good UX practise to design the form with single columns instead of multi-column

<blockquote>
5. Avoid placing questions side-by-side.

Eye-tracking studies have shown that simple one-column layouts are better than multi-column layouts with questions positioned side-by-side.

The only exception to this rule is when asking for dates (day, month, year) or time (hours and minutes), where multiple fields are expected to be on one line.
</blockquote>

Source- https://www.ventureharbour.com/form-design-best-practices/

Although there is a blog saying that multi-column form worked great for them but they were having 13 fields so it was very long.

Since the registration form just has 7 fields. It would be better to make them single column.

Also it would not be longer than this since the required error will go to the right side

<img width="748" alt="image" src="https://user-images.githubusercontent.com/15871340/66319144-3b133400-e93a-11e9-9af4-dba8542beb6c.png">

**Comment by itaditya** [comment]
Even NNGroup, the world leader in Research based UX suggests one-column layout https://www.nngroup.com/articles/web-form-design/

<blockquote>
Present fields in a single column layout. Multiple columns interrupt the vertical momentum of moving down the form. Rather than requiring users to visually reorient themselves, keep them in the flow by sticking to a single column with a separate row for each field. (Exceptions to this rule: short and/or logically related fields such as City, State, and Zip Code can be presented on the same row.)
</blockquote>

**Comment by kylemh** [comment]
I’ve messaged our designer this issue to confirm that it’s something we want to do!

**Comment by kylemh** [comment]
Feel free to tackle this. Note that you'll need to edit our form components such that the errors are showed to the right of the inputs. That'll be a bigger ask than one might think, as they're conditionally rendered and their content may span multiple lines.

**Comment by tusharpandey13** [comment]
Hi! I would like to take on this issue @kylemh

**Comment by kylemh** [comment]
Give it a shot!

**Comment by itaditya** [comment]
@kylemh I can add a prop which something like `errorAlign`. If it is explicitly set to `right` then I will align them to right otherwise they will come below only. This way all the other places where the Form Components are used won't be affected.

**Comment by tusharpandey13** [comment]
@itaditya according to that webpage, aren't ALL forms supposed to flow vertically only?

**Comment by kylemh** [comment]
The problem there is you'd still want to define styles for when `errorAlign="right"` correctly.

If you're gonna do that work anyways, might as well just make them all have their error messages render on the right, since it will look a lot better.

**Comment by itaditya** [comment]
@kylemh since I'm new to the project, I don't know how many places the Form is used and if it would be correct to align all errors to right. In case of a long form like say 13 fields, one study showed that it was better to have 2 column layout as otherwise the user finds the work exhausting.

I want to restrict the scope of the task to the registration page so that once that is done, we can one by one convert the forms to one column layout where they make sense. Places where the form is long we can keep 2 column layout so errors will be bottom. How does that sound?

**Comment by kylemh** [comment]
No form has more than 9 fields. Just do a global search for Form

**Comment by itaditya** [comment]
Registration form is done

![operation-code-registration-form](https://user-images.githubusercontent.com/15871340/66601002-7cb70f80-ebc4-11e9-8ae6-b998c9e10be8.gif)


I have absolute positioned the error messages when on desktop so that there is no reflow in the form elements.

**Comment by kylemh** [comment]
I look forward to the PR 🕺

**Comment by itaditya** [comment]
Please review it here https://github.com/OperationCode/front-end/pull/868
