### ISSUE TITLE
Integrate Cypress test coverage and combine reports with it and Jest `lcov` report

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#856]
# Feature request
We have unit test coverage, but that doesn't account for the code run in `pages`, where as Cypress _does_. We've abused jest's config surrounding ignored folders/files from coverage report and it gives us an unfairly happy representation our test coverage.

I'd like to remove a lot of that abuse, but can't do so unless we're reporting our entire test coverage accurately.

## Proposed solution
Use https://github.com/cypress-io/code-coverage and read https://glebbahmutov.com/blog/combined-end-to-end-and-unit-test-coverage/ to create a solution.

## Potential alternative solutions
We could also begin shipping our report as an `istanbul` report as opposed to `lcov` if that makes things easier (as long as Code Climate can read it)

**Comment by chynh** [comment]
Hey @kylemh, I've been playing around with this and I think I have something promising but I am not 100% sure since my experience in this topic is somewhat limited. Should I go ahead and make a PR or what would be the best way to go from here?

**Comment by kylemh** [comment]
PR for sure!

**Comment by anusha5695** [comment]
Hi Any updates on this?

**Comment by kylemh** [comment]
It's being actively worked on in #893
