### ISSUE TITLE
Sponsor logos are stretched

### ISSUE THREAD

**Issue by jasonappah** [OperationCode/front-end#874]
# Bug Report
## What is the current behavior?
Some of the logos are being stretched to 100x100 px. An example of this would be US Bank.

## What is the expected behavior?
The logos shouldn't be stretched and should appear at the correct aspect ratio.

## What steps did you take to get this behavior?
I opened the website up.

### Operating System
macOS 10.14.6 (Build 18G95)

It looks like in PartnerLogoLink.css, all logos are being forced to this size using the ```logo``` class. Would just taking out the height line fix the issue?
```
.logo {
  width: 100px;
  height: 100px;
  line-height: 50px;
  text-align: center;
  filter: grayscale(100%);
  transition: filter 0.2s linear;
}
```

### Browser
Google Chrome 77.0.3865.90

**Comment by kylemh** [comment]
Looks like US Bank is the one culprit. I'll just change the asset in s3.

Good catch!

**Comment by jasonappah** [comment]
Thanks!
