### ISSUE TITLE
Switch from `react-svg-loader` to `svgr`

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#876]
# Feature request
`react-svg-loader` may be the only issue preventing us from upgrading to the latest version of Storybook, and it routinely causes me issues in terms of using a very old version of `svgo`

## Proposed solution
Drop `react-svg-loader` integration from `.storybook/webpack.config.js` and `next.config.js`. Integrate `svgr` and ensure that our SVGO rules are obeyed (inside `common/config/svgo.js`

**Comment by vickywane** [comment]
Hi , i'd like to work on this .

**Comment by kylemh** [comment]
Closed in #877
