### ISSUE TITLE
Donate button UI improvement

### ISSUE THREAD

**Issue by shivam1192** [OperationCode/front-end#892]
# Feature request

Donate button UI doesn't match with the UI of other button like as of Learn more, Donate now etc.
## Proposed solution

What we can do is, after hovering to Donate button, the boundary and text color is of blue and entire filling of the button is of white color.   
## Potential alternative solutions

The UI after the changes become better and hence matches with the overall button throughout the website.

**Comment by kylemh** [comment]
It’s okay to have one-offs!

This would require a lot of design so I’m gonna close it. I appreciate you looking for things to contribute though.
