### ISSUE TITLE
Cannot register with apostrophies in name

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#947]
# Bug Report
## What is the current behavior?
Doing names like: N'golo or O'Hara are impossible due to incorrect validation of the name inputs.

## What is the expected behavior?
The name fields should have no validation.

## What steps did you take to get this behavior?
Noticed a Cypress test failing with randomly generated data

### Screenshots
![Screen Shot 2019-11-18 at 2 13 01 PM](https://user-images.githubusercontent.com/9523719/69098589-bffb6e00-0a0d-11ea-8efb-c703d20848c4.png)

**Comment by cmgonzales** [comment]
Hi Kyle,

can I try this?

Thanks

**Comment by kylemh** [comment]
Go ahead! Note: I've changed the expected behavior.

**Comment by aasifkhan7** [comment]
Hi,
Can I work on this issue?

**Comment by aasifkhan7** [comment]
I have generated a PR for the same:
https://github.com/OperationCode/front-end/pull/957
